/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Compra;

import Clientes.RegistroClientes;
import Conexiones.ConexionSQL;
import Empleados.RegistrarEmpleados;
import Proveedor.frm_proveedores;
import java.awt.Toolkit;
import Clientes.datos;
import static Venta.ModeloVenta.rolth;
import static Venta.ModeloVenta.txtvendedor;
import static Venta.ModeloVenta.usuariosth;
import inicio_sesion.Pantalla_Inicio_Sesion;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menuPrincipal;
import producto.Producto;
import org.apache.log4j.*;
/**
 *
 * @author Hector
 */
public class ModeloCompra1 extends javax.swing.JFrame {
 final static org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(ModeloCompra1.class);
    public ModeloCompra1() {
        initComponents();
        PropertyConfigurator.configure("log4j.properties");
        this.setLocationRelativeTo(null);
        mostrardatos("");
        txtcai.setText("317976-7A6111-0B419A-638143-5FA2D6-98");
        
        Calendar cal= Calendar.getInstance();
        String fecha;
        fecha = cal.get(Calendar.YEAR)+"-"+cal.get(Calendar.MONTH)+"-"+cal.get(Calendar.DATE)+" "+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+":"+cal.get(Calendar.SECOND);
        
        
    }

    void mostrardatos(String valor) {
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Id Detalle");
        modelo.addColumn("Producto ");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Monto");

        jTable1.setModel(modelo);
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM detallecompra";
        } else {
            sql = "SELECT * FROM detallecompra WHERE (Idcompra='" + valor + "'OR compra_idc ='" + valor + "'OR producto_id ='" + valor + "'OR cantidadcompra ='" + valor + "'OR preciocompra='" + valor + "')";
        }

        String[] datos = new String[5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);

                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdcliente1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtserie = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtcai = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBuscarCli = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        btnAddprecio = new javax.swing.JButton();
        spinCant = new javax.swing.JSpinner();
        txtcli = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtprod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtisv = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        rSLabelFecha1 = new rojeru_san.RSLabelFecha();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnventa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtotalapagar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        subt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        usuarioslh = new javax.swing.JLabel();
        rollh = new javax.swing.JLabel();
        vendedorlh = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Factura de Compra \"Servicios Múltiples Cueva\"");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("\"Así abrimos, día a día, el camino del fúturo...\"");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tel: 9927-5893");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nº Factura");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        txtserie.setEditable(false);
        txtserie.setBackground(new java.awt.Color(204, 204, 204));
        txtserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserieActionPerformed(evt);
            }
        });
        txtserie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtserieKeyTyped(evt);
            }
        });
        jPanel1.add(txtserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 90, 300, 34));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("CAI");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        txtcai.setEditable(false);
        txtcai.setBackground(new java.awt.Color(204, 204, 204));
        txtcai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcaiKeyTyped(evt);
            }
        });
        jPanel1.add(txtcai, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 300, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, 180));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("COD:PROVEEDOR:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        txtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodClienteActionPerformed(evt);
            }
        });
        txtCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodClienteKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 119, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("COD: PRODUCTO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txtCodProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProductoActionPerformed(evt);
            }
        });
        txtCodProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 119, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("PRECIO:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        txtprecio.setEditable(false);
        jPanel2.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 119, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("CANTIDAD:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        btnBuscarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar (1).jpg"))); // NOI18N
        btnBuscarCli.setText("Buscar");
        btnBuscarCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliMouseClicked(evt);
            }
        });
        btnBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 100, -1));

        btnBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar (1).jpg"))); // NOI18N
        btnBuscarProd.setText("Buscar");
        btnBuscarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProdMouseClicked(evt);
            }
        });
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 100, 30));

        btnAddprecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.jpg"))); // NOI18N
        btnAddprecio.setText("Agregar");
        btnAddprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddprecioActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 100, -1));

        spinCant.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        spinCant.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinCantStateChanged(evt);
            }
        });
        spinCant.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spinCantPropertyChange(evt);
            }
        });
        jPanel2.add(spinCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 119, 30));

        txtcli.setEditable(false);
        txtcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcliActionPerformed(evt);
            }
        });
        jPanel2.add(txtcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 178, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("PRODUC:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        txtprod.setEditable(false);
        jPanel2.add(txtprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 180, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("ISV:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("PROVEEDOR:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        txtisv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "15", "18" }));
        txtisv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtisvActionPerformed(evt);
            }
        });
        jPanel2.add(txtisv, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel14.setText("FECHA:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, 20));

        rSLabelFecha1.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelFecha1.setFormato("yyyy-MM-dd\n");
        jPanel2.add(rSLabelFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 760, 180));

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Facturas Detalle");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(306, 306, 306))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 760, 210));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.jpg"))); // NOI18N
        btnventa.setText("Registrar Compra");
        btnventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventaActionPerformed(evt);
            }
        });
        jPanel4.add(btnventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 160, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirfactura.jpg"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 90, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasfactura.jpg"))); // NOI18N
        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verfacturas.jpg"))); // NOI18N
        jButton4.setText("Ver Facturas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.jpg"))); // NOI18N
        jButton5.setText("Cancelar Factura");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 160, -1));

        txtotalapagar.setEditable(false);
        txtotalapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotalapagarActionPerformed(evt);
            }
        });
        jPanel4.add(txtotalapagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 120, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Total a Pagar:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevofactura.jpg"))); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 110, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 760, 130));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde3.jpg"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 720));

        subt.setEditable(false);
        subt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtActionPerformed(evt);
            }
        });
        getContentPane().add(subt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 120, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Monto x Producto");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, 20));
        getContentPane().add(usuarioslh, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 700, 40, 10));
        getContentPane().add(rollh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 700, 20, 20));
        getContentPane().add(vendedorlh, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 700, 20, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtotalapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotalapagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotalapagarActionPerformed

    private void btnBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscarCliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Object[] options = {"SI", "NO"};
         int i = JOptionPane.showOptionDialog(null, "Esta seguro que desea salir del sistema?","Seleccione una opción",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icono("/Imagenes/logo.png", 40, 40),  options, options[0]);
        
        if (i == 0) { 
            logger.info("salio del sistema");
        System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void txtCodClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodClienteKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCodClienteKeyReleased

    void calularTotal() {
        /*        tpagar = 0;
         for (int i = 0; i < jTable1.getRowCount(); i++) {
         cant = Integer.parseInt(jTable1.getValueAt(i, 3).toString());
         pre = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
         tpagar = tpagar + (cant * pre);

         }
         txtotalapagar.setText("" + tpagar + "");
         */
    }


    private void btnBuscarCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliMouseClicked
        // TODO add your handling code here:
        if(txtCodCliente.getText().length() == 1 || txtCodCliente.getText().length() == 2 || txtCodCliente.getText().length() == 3){
        
        try {
            String num_id_cliente = txtCodCliente.getText();

            ConexionSQL cc = new ConexionSQL();
            Connection nn = cc.getConnection();
           
                    

            PreparedStatement pst = nn.prepareStatement("SELECT * FROM proveedor where (Empresa_id=?)");
            
            
            
            pst.setString(1, num_id_cliente);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtcli.setText(rs.getString("Nombre_Empresa"));
                 logger.info("busca uno de los proveedores");
            } else {
                JOptionPane.showMessageDialog(null, "La empresa no esta registrada no se encuentra registrada");
                 logger.debug("no se encontro al proveedor deseado");
            }
        } catch (Exception e) {
        }
         
         }else if(txtCodCliente.getText().length() == 14){
              try {
            String num_id_cliente = txtCodCliente.getText();

            ConexionSQL cc = new ConexionSQL();
            Connection nn = cc.getConnection();
           
                    

            PreparedStatement pst = nn.prepareStatement("SELECT * FROM proveedor where (rtn_empresa =?)");
            
            
            
            pst.setString(1, num_id_cliente);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtcli.setText(rs.getString("Nombre_Empresa"));
            } else {
                JOptionPane.showMessageDialog(null, "La Empresa no se encuentra registrada");
            }
        } catch (Exception e) {
        }
         
         }
    }//GEN-LAST:event_btnBuscarCliMouseClicked

    private void btnBuscarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProdMouseClicked
        // TODO add your handling code here:
        try {
            int nombre = Integer.parseInt(txtCodProducto.getText());

            ConexionSQL cc = new ConexionSQL();
            Connection nn = cc.getConnection();

            PreparedStatement pst = nn.prepareStatement("Select * from productos where IdProducto =?");

            pst.setInt(1, nombre);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                txtprod.setText(rs.getString("Nombre"));
                txtprecio.setText(rs.getString("Precio"));
                 logger.info("busca un producto");
            } else {
                JOptionPane.showMessageDialog(null, "El Producto no se encuentra registrado");
                 logger.info("no se encontro el producto deseado");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscarProdMouseClicked

    private void spinCantStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinCantStateChanged
        double role = Integer.parseInt(spinCant.getValue().toString());
        double prec = Integer.parseInt(txtprecio.getText());

        double pre = Integer.parseInt(txtprecio.getText().toString());
        double princi = Integer.parseInt(txtisv.getSelectedItem().toString());

        double secon = princi * 0.01;
        double terc = secon * pre;
        double to = terc + pre;

        double tot = role * to;

        subt.setText(String.valueOf(Math.round(tot)));


    }//GEN-LAST:event_spinCantStateChanged

    private void btnAddprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddprecioActionPerformed
        if (txtCodProducto.getText().equals("") || txtprecio.getText().equals("") || subt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos los campos tienen que ir llenos");
             logger.info("Error, los campos van vacios");
        } else {
            if (spinCant.getValue().toString().startsWith("1")|| spinCant.getValue().toString().startsWith("2")|| spinCant.getValue().toString().startsWith("3")|| spinCant.getValue().toString().startsWith("4") 
                    || spinCant.getValue().toString().startsWith("5")||spinCant.getValue().toString().startsWith("6")|| spinCant.getValue().toString().startsWith("7")|| spinCant.getValue().toString().startsWith("8") 
                    || spinCant.getValue().toString().startsWith("9")){
                 
            DefaultTableModel model = new DefaultTableModel();

            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                txtserie.getText(),
                txtCodProducto.getText(),
                spinCant.getValue().toString(),
                txtprecio.getText(),
                subt.getText()

            });

            txtCodProducto.setText("");

            txtprod.setText("");
            
            }else{
            JOptionPane.showMessageDialog(null, "La cantidad a llevar no puede ser 0");
            logger.info("el campo de cantidad no puede ir en 0");
            }
        }

        double sum = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {

            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 4).toString());

        }
        Math.round(sum);

        txtotalapagar.setText(String.valueOf(sum));
        
        spinCant.setValue(0);

        
    }//GEN-LAST:event_btnAddprecioActionPerformed
   /* void detallefactura(){
        for(int j = 0;j<jTable1.getRowCount();j++){
            ConexionSQL cc = new ConexionSQL();
            Connection cn = cc.getConnection();
            
            try{
            PreparedStatement pst = cn.prepareStatement("INSERT INTO detallecompra(Idcompra,compra_idc,producto_id,cantidadcompra,preciocompra) VALUES(NULL,?,?,?,?)");
            pst.setString(1, jTable1.getValueAt(j, 0).toString());
            pst.setString(2, jTable1.getValueAt(j, 1).toString());
            }catch(Exception e){
            }
        }
    }*/
    
    
    void limpiar() {
        txtserie.setText("");
        txtCodCliente.setText("");

        txtisv.setSelectedItem("0");
       
        subt.setText("");
        spinCant.setValue("");
        txtprecio.setText(null);
        txtcli.setText("");
        txtprod.setText("");

        txtcli.setText("");

    }

    void sumar() {
        int fila = 0;
        int total = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            fila = Integer.parseInt(jTable1.getValueAt(i, 5).toString());
            total += fila;
        }

    }
    private void btnventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventaActionPerformed

        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        
        try {

            PreparedStatement pst = cn.prepareStatement("INSERT INTO `compra` (`Idcompra`, `Proveedor_IdProveedor`, `cai`, `monto`, `isv`,`fecha_registro`) VALUES (NULL, ?, ?, ?, ?, ?)");
            
            pst.setString(1, txtCodCliente.getText());
            pst.setString(2, txtcai.getText());
            pst.setString(3, txtotalapagar.getText());
            pst.setString(4, txtisv.getSelectedItem().toString());
            pst.setString(5, rSLabelFecha1.getFecha());
            
            

            int a = pst.executeUpdate();
            if (a > 0) {
                JOptionPane.showMessageDialog(null, "Registro exitoso");
                logger.info("se registra exitosamente la factura");
                sumar();
                limpiar();
                mostrardatos("");
                
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
                logger.info("hubo error al agregar la factura");
            }

        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e);
        }
    txtcai.setText("317976-7A6111-0B419A-638143-5FA2D6-98");

    }//GEN-LAST:event_btnventaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Object[] options = {"SI", "NO"};
         int i = JOptionPane.showOptionDialog(null, "Esta seguro que desea volver al menu principal?","Seleccione una opción",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icono("/Imagenes/logo.png", 40, 40),  options, options[0]);
        
        if (i == 0) { 
            
            logger.info("Vuelve al menu principal");
        
            menuPrincipal mp = new menuPrincipal();
            mp.setVisible(true);
        this.dispose();
       
        }
         menuPrincipal.nombre.setText(usuarioslh.getText());
        menuPrincipal.rol.setText(rollh.getText());        
        menuPrincipal.idv.setText(vendedorlh.getText());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCodClienteActionPerformed

    private void txtCodClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodClienteKeyPressed

    private void txtCodClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodClienteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (txtCodCliente.getText().length() >= 14) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodClienteKeyTyped

    private void txtCodProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (txtCodProducto.getText().length() >= 5) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodProductoKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        logger.info("Entra a la pantalla para observar las facturas");
        VerFacturaCompra ver = new VerFacturaCompra();
        ver.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    public Icon icono(String path, int width, int height){
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().
                getScaledInstance(width,height,java.awt.Image.SCALE_SMOOTH));
        return img;
    }
    
    
    //bro me fui a dejar unas mascarillas xdd pero ya lo termine 
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Object[] options = {"SI", "NO"};
        int i = JOptionPane.showOptionDialog(null, "Esta seguro que desea eliminar el registro?","Seleccione una opcion",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icono("/Imagenes/logo.png", 40, 40),  options, options[0]);
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        int fila = jTable1.getSelectedRow();
        
        txtcai.setText("317976-7A6111-0B419A-638143-5FA2D6-98");
        txtprecio.setText("");
        txtcli.setText("");
        txtotalapagar.setText("");
                
        String cod = "";
        if(i==0){
        cod = jTable1.getValueAt(fila, 1).toString();
        try {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM detallecompra WHERE producto_id= '" + cod + "'");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Se cancela la factura con exito");
            logger.info("Se cancelo la factura con exito");
            mostrardatos("");// TODO add your handling code here:
        } catch (Exception e) {
        }
         
        limpiar();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCodProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProductoActionPerformed

    private void txtserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserieActionPerformed

    private void txtserieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserieKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtserieKeyTyped

    private void txtcaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaiKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaiKeyTyped

    private void txtcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcliActionPerformed

    private void spinCantPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spinCantPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_spinCantPropertyChange

    private void subtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        int fila = jTable1.getSelectedRow();
        
        txtcai.setText("317976-7A6111-0B419A-638143-5FA2D6-98");
        txtprecio.setText("");
        txtcli.setText("");
        txtotalapagar.setText("");
                
        String cod = "";
        
        cod = jTable1.getValueAt(fila, 1).toString();
        try {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM detallecompra WHERE producto_id= '" + cod + "'");
            pst.executeUpdate();
           
            mostrardatos("");// TODO add your handling code here:
        } catch (Exception e) {
        }
         logger.info("limpio todo el espacio de la factura ");
        limpiar();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtisvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtisvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtisvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeloCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeloCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeloCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeloCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModeloCompra1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddprecio;
    private javax.swing.JButton btnBuscarCli;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnventa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private rojeru_san.RSLabelFecha rSLabelFecha1;
    public static javax.swing.JLabel rollh;
    private javax.swing.JSpinner spinCant;
    private javax.swing.JTextField subt;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtIdcliente1;
    private javax.swing.JTextField txtcai;
    private javax.swing.JTextField txtcli;
    private javax.swing.JComboBox txtisv;
    private javax.swing.JTextField txtotalapagar;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprod;
    private javax.swing.JTextField txtserie;
    public static javax.swing.JLabel usuarioslh;
    public static javax.swing.JLabel vendedorlh;
    // End of variables declaration//GEN-END:variables

}
