/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularioCompra;

import Clientes.RegistroClientes;
import Conexiones.ConexionSQL;
import Empleados.RegistrarEmpleados;
import Proveedor.frm_proveedores;
import formularios.Interfaz;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menuPrincipal;
import producto.Producto;

/**
 *
 * @author Hector
 */
public class InterfazCompra extends javax.swing.JFrame {
    ConexionSQL cc = new ConexionSQL();
    Connection con = cc.getConnection();
    
    
    

    /**
     * Creates new form Interfaz
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public InterfazCompra() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        MostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdcliente1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labIdfactura = new javax.swing.JLabel();
        labIdfactura1 = new javax.swing.JLabel();
        labIdfactura2 = new javax.swing.JLabel();
        labIdfactura3 = new javax.swing.JLabel();
        labIdfactura4 = new javax.swing.JLabel();
        labIdfactura5 = new javax.swing.JLabel();
        labIdfactura6 = new javax.swing.JLabel();
        labIdfactura7 = new javax.swing.JLabel();
        labIdfactura8 = new javax.swing.JLabel();
        labIdfactura10 = new javax.swing.JLabel();
        txtIdfactura = new javax.swing.JTextField();
        txtIsv2 = new javax.swing.JTextField();
        txtCai = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtIdempleado = new javax.swing.JTextField();
        txtIsv1 = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        cbxTipopago = new javax.swing.JComboBox<String>();
        cbxDescripcionservicio = new javax.swing.JComboBox<String>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFacturaVenta = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        labIdfactura11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura de Ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labIdfactura.setText("ID Factura");
        jPanel1.add(labIdfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 94, -1));

        labIdfactura1.setText("Cai");
        jPanel1.add(labIdfactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 94, -1));

        labIdfactura2.setText("Id Empleado");
        jPanel1.add(labIdfactura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 94, -1));

        labIdfactura3.setText("15% isv");
        jPanel1.add(labIdfactura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 94, -1));

        labIdfactura4.setText("Total");
        jPanel1.add(labIdfactura4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 94, 23));

        labIdfactura5.setText("Cantidad");
        jPanel1.add(labIdfactura5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 94, 23));

        labIdfactura6.setText("Tipo de Pago");
        jPanel1.add(labIdfactura6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 94, 23));

        labIdfactura7.setText("Producto");
        jPanel1.add(labIdfactura7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, 23));

        labIdfactura8.setText("Fecha");
        jPanel1.add(labIdfactura8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 54, -1));

        labIdfactura10.setText("18% isv");
        jPanel1.add(labIdfactura10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 94, -1));
        jPanel1.add(txtIdfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 121, -1));
        jPanel1.add(txtIsv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 121, -1));
        jPanel1.add(txtCai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 121, -1));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 121, -1));
        jPanel1.add(txtIdempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 121, -1));
        jPanel1.add(txtIsv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 121, -1));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 121, -1));

        cbxTipopago.setForeground(new java.awt.Color(0, 0, 204));
        cbxTipopago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Tarjeta " }));
        jPanel1.add(cbxTipopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 121, -1));

        cbxDescripcionservicio.setForeground(new java.awt.Color(0, 0, 204));
        cbxDescripcionservicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Intalación de Cámaras de Seguridad", "Mantenimiento Planta Telefónica", " " }));
        jPanel1.add(cbxDescripcionservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 121, -1));

        jDateChooser1.setForeground(new java.awt.Color(0, 0, 204));
        jDateChooser1.setDateFormatString("d MMMM, yyyy");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        TablaFacturaVenta.setForeground(new java.awt.Color(0, 0, 204));
        TablaFacturaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaFacturaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFacturaVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFacturaVenta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 70, 750, 92));

        btnGuardar.setBackground(new java.awt.Color(0, 0, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.MatteBorder(null));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 69, 20));

        btnNuevo.setBackground(new java.awt.Color(0, 0, 204));
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 69, -1));

        btnEditar.setBackground(new java.awt.Color(0, 0, 204));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 69, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 0, 204));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        btnSalir.setBackground(new java.awt.Color(0, 153, 204));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 69, -1));

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 121, -1));

        labIdfactura11.setText("Búsqueda");
        jPanel1.add(labIdfactura11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 70, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 204));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Inicio");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jButton9.setBackground(new java.awt.Color(0, 0, 204));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Registrar Empleado");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jButton10.setBackground(new java.awt.Color(0, 0, 204));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Registrar Cliente");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jButton11.setBackground(new java.awt.Color(0, 0, 204));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Registrar Proveedor");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jButton12.setBackground(new java.awt.Color(0, 0, 204));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Registrar Producto");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jButton13.setBackground(new java.awt.Color(0, 0, 204));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Registrar Compra");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        jButton14.setBackground(new java.awt.Color(0, 153, 204));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Atras");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("REGISTRAR COMPRA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            InsertarDatos();
            LimpiarCajas();
            MostrarDatos();
        } catch (Exception e) {
            Logger.getLogger(InterfazCompra.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
      // LimpiarCajas();
      txtBusqueda.setText( Date.valueOf("12/12/2020").toString());
               
 
       
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void TablaFacturaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFacturaVentaMouseClicked
          int filaSeleccionada = TablaFacturaVenta.rowAtPoint(evt.getPoint());
          
        txtIdfactura.setText(TablaFacturaVenta.getValueAt(filaSeleccionada,1).toString());
        txtCai.setText(TablaFacturaVenta.getValueAt(filaSeleccionada,2).toString());
        txtIdempleado.setText(TablaFacturaVenta.getValueAt(filaSeleccionada,3).toString());
        txtIsv1.setText(TablaFacturaVenta.getValueAt(filaSeleccionada,4).toString());
        txtIsv2.setText(TablaFacturaVenta.getValueAt(filaSeleccionada,5).toString());
        txtCantidad.setText(TablaFacturaVenta.getValueAt(filaSeleccionada,6).toString());
        txtCantidad.setText(TablaFacturaVenta.getValueAt(filaSeleccionada,7).toString());
        cbxTipopago.setSelectedItem(TablaFacturaVenta.getValueAt(filaSeleccionada,8));
        cbxDescripcionservicio.setSelectedItem(TablaFacturaVenta.getValueAt(filaSeleccionada,9));
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_TablaFacturaVentaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        EditarDatos();
        MostrarDatos();
        LimpiarCajas();
       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        EliminarDatos();
        MostrarDatos();
        LimpiarCajas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        FiltrarDatos(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyReleased

 
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
       System.exit(0);
       
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Producto prod = new Producto();
        prod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        menuPrincipal menu = new menuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        RegistrarEmpleados re = new RegistrarEmpleados();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        RegistroClientes rc = new RegistroClientes();
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
       frm_proveedores prov = new frm_proveedores();
       prov.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Interfaz venta = new Interfaz();
        venta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        menuPrincipal menu = new menuPrincipal();
        menu.setVisible(true);
        this.dispose();        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton14ActionPerformed
public void InsertarDatos(){
    try{
        String SQL = "insert into FacturaCompra (Idfactura,Cai,IdProveedor,Isv1,Isv2,Cantidad,Total,Tipopago,Descripcionservicio,Fecha)"
                + "values (?,?,?,?,?,?,?,?,?,12/12/2020)";
       
        PreparedStatement pst = con.prepareStatement(SQL);
        
        pst.setInt(1,Integer.parseInt(txtIdfactura.getText()));
        pst.setInt(2,Integer.parseInt(txtCai.getText()));
        pst.setInt(3,Integer.parseInt(txtIdempleado.getText()));
        pst.setDouble(4,Double.parseDouble(txtIsv1.getText()));
        pst.setDouble(5,Double.parseDouble(txtIsv2.getText()));
        pst.setDouble(6,Double.parseDouble(txtCantidad.getText()));
        pst.setDouble(7,Double.parseDouble(txtTotal.getText()));
        pst.setString(8, cbxTipopago.getSelectedItem().toString());
        pst.setString(9, cbxDescripcionservicio.getSelectedItem().toString());
        
        //pst.setDate(11,Date.valueOf("12/12/2020"));
        pst.execute()
        ;
      JOptionPane.showMessageDialog(null, "Se ha Guardado Exitosamente el Registro");
            
    }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Error al Guardar  el Registro"+e);
    }
}

public void EditarDatos(){
    try{
        String SQL = "update FacturaVenta set IdProveedor = ?,Cai =?,Idempleado=?,Isv1=?,"
                + "Isv2=?,Cantidad=?,Total=?,Tipopago=?,"
                + "Descripcionservicio=? where Idfactura=? ";
        
        int filaseleccionado = TablaFacturaVenta.getSelectedRow();
        String oyetu = (String)TablaFacturaVenta.getValueAt(filaseleccionado , 0);
        PreparedStatement pst = con.prepareStatement(SQL);
        
        pst.setInt(1,Integer.parseInt(txtIdfactura.getText()));
        pst.setInt(2,Integer.parseInt(txtCai.getText()));
        pst.setInt(3,Integer.parseInt(txtIdempleado.getText()));
        pst.setDouble(4,Double.parseDouble(txtIsv1.getText()));
        pst.setDouble(5,Double.parseDouble(txtIsv2.getText()));
        pst.setDouble(6,Double.parseDouble(txtCantidad.getText()));
        pst.setDouble(7,Double.parseDouble(txtTotal.getText()));
        
        int seleccionado = cbxTipopago.getSelectedIndex();
        pst.setString(8, cbxTipopago.getItemAt(seleccionado));
        
        int seleccionado1 = cbxDescripcionservicio.getSelectedIndex();
        pst.setString(9, cbxDescripcionservicio.getItemAt(seleccionado1));
        
        pst.setString(10, oyetu);
 
        pst.execute()
        ;
      JOptionPane.showMessageDialog(null, "Se ha Editado Exitosamente el Registro");
            
    }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Error al Editar  el Registro");
    }
}

public void LimpiarCajas(){
    txtIdfactura.setText("");
    txtCai.setText("");
    txtIdempleado.setText("");
    txtIsv1.setText("");
    txtIsv2.setText("");
    txtCantidad.setText("");
    txtTotal.setText("");
    cbxTipopago.setSelectedItem(null);
    cbxDescripcionservicio.setSelectedItem(null);
}


public void EliminarDatos(){
    
    int filSeleccionada=TablaFacturaVenta.getSelectedRow();
    try{
        String SQL = "delete from facturaventa where id= " + TablaFacturaVenta.getValueAt(filSeleccionada,0);
        Statement st = con.createStatement();
        int n = st.executeUpdate(SQL);
        if(n>=0);{
    JOptionPane.showMessageDialog(null, "Registro Eliminado" );
}}catch(Exception e){
    JOptionPane.showMessageDialog(null, "Error al Eliminar el Registro" + e.getMessage());
}
}

public void FiltrarDatos(String Valor){
    String[]titulos ={"Id factura","Cai","Id Proveedor","15% Isv", "18% isv", "Cantidad Producto",
            "Total Venta", "Tipo Pago","Descripción Setvicio"};
    
    String[]registros = new String[10];
    DefaultTableModel modelo= new DefaultTableModel(null,titulos);
    String SQL = "select * from facturaventa where Idfactura like '%" +Valor+"%'";
    try{
        Statement st= con.createStatement();
        ResultSet rs = st.executeQuery(SQL);
        while(rs.next()){
        registros[0]=rs.getString("Idfactura");
        registros[1]=rs.getString("Cai");
        registros[2]=rs.getString("Idempleado");
        registros[3]=rs.getString("Isv1");
        registros[4]=rs.getString("Isv2");
        registros[5]=rs.getString("Cantidad");
        registros[6]=rs.getString("Total");
        registros[7]=rs.getString("Tipopago");
        registros[8]=rs.getString("Descripcionservicio");
       
        
        modelo.addRow(registros);   
        } TablaFacturaVenta.setModel(modelo);
    }catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error al Mostrar Datos"+ e.getMessage());
    }
}

public void MostrarDatos(){
    String[]titulos ={"Id factura","Cai","Id Empleado","15% Isv", "18% isv", "Cantidad Producto",
            "Total Venta", "Tipo Pago","Descripción Setvicio"};
    
    String[]registros = new String[10];
    DefaultTableModel modelo= new DefaultTableModel(null,titulos);
    String SQL = "select * from facturaventa";
    try{
        Statement st= con.createStatement();
        ResultSet rs = st.executeQuery(SQL);
        while(rs.next()){
        registros[0]=rs.getString("Idfactura");
        registros[1]=rs.getString("Cai");
        registros[2]=rs.getString("Idempleado");
        registros[3]=rs.getString("Isv1");
        registros[4]=rs.getString("Isv2");
        registros[5]=rs.getString("Cantidad");
        registros[6]=rs.getString("Total");
        registros[7]=rs.getString("Tipopago");
        registros[8]=rs.getString("Descripcionservicio");
        
        
        modelo.addRow(registros);   
        } TablaFacturaVenta.setModel(modelo);
    }catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error al Mostrar Datos"+ e.getMessage());
    }
}

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfazCompra().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFacturaVenta;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxDescripcionservicio;
    private javax.swing.JComboBox<String> cbxTipopago;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labIdfactura;
    private javax.swing.JLabel labIdfactura1;
    private javax.swing.JLabel labIdfactura10;
    private javax.swing.JLabel labIdfactura11;
    private javax.swing.JLabel labIdfactura2;
    private javax.swing.JLabel labIdfactura3;
    private javax.swing.JLabel labIdfactura4;
    private javax.swing.JLabel labIdfactura5;
    private javax.swing.JLabel labIdfactura6;
    private javax.swing.JLabel labIdfactura7;
    private javax.swing.JLabel labIdfactura8;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCai;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdcliente1;
    private javax.swing.JTextField txtIdempleado;
    private javax.swing.JTextField txtIdfactura;
    private javax.swing.JTextField txtIsv1;
    private javax.swing.JTextField txtIsv2;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    
}
