/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClienteMenu;

import Clientes.*;
import Compra.ModeloCompra1;
import Conexiones.ConexionSQL;
import Empleados.RegistrarEmpleados;
import Proveedor.frm_proveedores;
import Venta.ModeloVenta;
import VentasEmpleado.VentaEm;
import contactos.contacto_cliente.ContactoC;
import java.awt.Color;
import java.awt.Toolkit;
//import FacturaCompra.FacturaCompra;
/*import Factura_Venta.Factura_Venta;*/
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menuPrincipal;

import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.*;

/**
 *
 * @author luisc
 */
public class RegistroClientesFacEm extends javax.swing.JFrame {

    /**
     * Creates new form RegistroClientes
     */
    final static org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(RegistroClientesFacEm.class);
    public RegistroClientesFacEm() {
        initComponents();
        mostrardatos("");
        PropertyConfigurator.configure("log4j.properties");
        
     this.setLocationRelativeTo(null);
    }
    
    ConexionSQL cc = new ConexionSQL();
    Connection cn = cc.getConnection();
    
    
    
    
    void mostrardatos(String valor){
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        DefaultTableModel modelo2 = new DefaultTableModel();
        
        modelo2.addColumn("ID Cliente");
        modelo2.addColumn("Nombre Cliente");
        modelo2.addColumn("Apellido Cliente");
        modelo2.addColumn("Direccion");
        modelo2.addColumn("Numero de indentidad");
        modelo2.addColumn("RTN Cliente");
        
        
        
        tablaclientes.setModel(modelo2);
        String sql = "";
        if (valor.equals(""))
        {
            sql="SELECT * FROM cliente";
        }
        else{
            sql= "SELECT * FROM cliente WHERE (Cli_id ='" +valor+ "'OR Nombre_Cliente='" +valor+"'OR Apellido_Cliente='"+valor+"'OR rtn_Cliente='"+valor+"'OR Num_Identidad_cliente='" +valor+"'OR Direccion_Cliente='"+valor+"')";
        }  
        
        String [] datos = new String[6];
        try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                
                modelo2.addRow(datos);
            }
            tablaclientes.setModel(modelo2);
        }catch (SQLException ex){
           Logger.getLogger(datos.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre_cli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_rtn_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cli_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        txt_apellido_cli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_nuevo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_num_id_cli = new javax.swing.JTextField();
        txt_dir_cli = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        buscar_txt = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jMenuItem2.setText("Modificar");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Registro Clientes");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel3.setText("Nombre Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        txt_nombre_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_cliActionPerformed(evt);
            }
        });
        txt_nombre_cli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_cliKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 160, 30));

        jLabel4.setText("RTN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        txt_rtn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rtn_clienteActionPerformed(evt);
            }
        });
        txt_rtn_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rtn_clienteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_rtn_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 160, 30));

        jLabel5.setText("ID Cliente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        txt_cli_id.setEditable(false);
        txt_cli_id.setBackground(new java.awt.Color(204, 204, 204));
        txt_cli_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_cli_idMouseClicked(evt);
            }
        });
        txt_cli_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cli_idActionPerformed(evt);
            }
        });
        txt_cli_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cli_idKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cli_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 160, 30));

        jLabel7.setText("Dirección");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        btn_guardar.setBackground(new java.awt.Color(0, 0, 204));
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 80, -1));

        tablaclientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaclientes.setForeground(new java.awt.Color(0, 0, 204));
        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaclientes.setComponentPopupMenu(jPopupMenu2);
        tablaclientes.getTableHeader().setReorderingAllowed(false);
        tablaclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaclientes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 622, 117));

        txt_apellido_cli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellido_cliKeyTyped(evt);
            }
        });
        getContentPane().add(txt_apellido_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 160, 30));

        jLabel9.setText("Apellido Cliente");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        btn_nuevo.setBackground(new java.awt.Color(0, 0, 255));
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 80, -1));

        jLabel10.setText("Número de Identidad");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        txt_num_id_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num_id_cliActionPerformed(evt);
            }
        });
        txt_num_id_cli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_num_id_cliKeyTyped(evt);
            }
        });
        getContentPane().add(txt_num_id_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 160, 30));

        txt_dir_cli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dir_cliKeyTyped(evt);
            }
        });
        getContentPane().add(txt_dir_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 160, 70));

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        buscar_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_txtActionPerformed(evt);
            }
        });
        getContentPane().add(buscar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 140, 30));

        jButton6.setBackground(new java.awt.Color(0, 153, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Atrás");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 80, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 204));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Mostrar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 70, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde3.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
       ConexionSQL cc = new ConexionSQL();
       Connection cn = cc.getConnection();
       if(txt_dir_cli.getText().contains("!") || txt_dir_cli.getText().contains("~")|| txt_dir_cli.getText().contains("`")||
                   txt_dir_cli.getText().contains("@") || txt_dir_cli.getText().contains("$") || txt_dir_cli.getText().contains("%")||
                    txt_dir_cli.getText().contains("^")||txt_dir_cli.getText().contains("&")||txt_dir_cli.getText().contains("*")||
                    txt_dir_cli.getText().contains("(")||txt_dir_cli.getText().contains(")")||txt_dir_cli.getText().contains("-")||
                    txt_dir_cli.getText().contains("_")||txt_dir_cli.getText().contains("+")||txt_dir_cli.getText().contains("=")){
                    
                    
            JOptionPane.showMessageDialog(null,"No se permiten caracteres especiales a parte del # y el .");
            logger.debug("Error, inserto caracteres especiales");
            }else{
        if(txt_dir_cli.getText().equals("!") || txt_dir_cli.getText().equals("~")|| txt_dir_cli.getText().equals("`")||
                   txt_dir_cli.getText().equals("@") || txt_dir_cli.getText().equals("$") || txt_dir_cli.getText().equals("%")||
                    txt_dir_cli.getText().equals("^")||txt_dir_cli.getText().equals("&")||txt_dir_cli.getText().equals("*")||
                    txt_dir_cli.getText().equals("(")||txt_dir_cli.getText().equals(")")||txt_dir_cli.getText().equals("-")||
                    txt_dir_cli.getText().equals("_")||txt_dir_cli.getText().equals("+")||txt_dir_cli.getText().equals("=")){
                    
                    
            JOptionPane.showMessageDialog(null,"No se permiten caracteres especiales a parte del # y el .");
            logger.info("Error, inserto caracteres especiales");
            }else{
        if(txt_rtn_cliente.getText().equals("") || txt_nombre_cli.getText().equals("")
            || txt_apellido_cli.getText().equals("") || txt_num_id_cli.getText().equals("")
            || txt_dir_cli.getText().equals("")){
        
        JOptionPane.showMessageDialog(null, "Hay Campos que estan vacios debe llenar todos los campos"); 
                    logger.debug("Error, trato de guardar con caracteres vacios");

    
    }else{
       
       try{
           if(existeUsuario(txt_cli_id.getText())==0){
                           logger.debug("Error, trato de registrar un id que ya existia");

            if(txt_num_id_cli.getText().length() >= 13){
                if (txt_num_id_cli.getText().startsWith("0") || txt_num_id_cli.getText().startsWith("1")) {
                    if (txt_rtn_cliente.getText().startsWith("0") || txt_rtn_cliente.getText().startsWith("1")) {
                    if(txt_rtn_cliente.getText().length() >=14){
                        if(existeId(txt_num_id_cli.getText())==0){
                            if(existeRTN(txt_rtn_cliente.getText())==0){
           
           PreparedStatement pst = cn.prepareStatement("INSERT INTO `cliente` (`Cli_id`, `Nombre_Cliente`, `Apellido_Cliente`, `Direccion_Cliente`, `Num_Identidad_cliente`, `rtn_Cliente`, `contactoid`) VALUES (NULL, ?, ?, ?, ?, ?, NULL);");
                
           pst.setString(1, txt_nombre_cli.getText());
           pst.setString(3, txt_dir_cli.getText());
           pst.setString(2, txt_apellido_cli.getText());
           pst.setString(4, txt_num_id_cli.getText());
                pst.setString(5, txt_rtn_cliente.getText()); 
                    
           int a = pst.executeUpdate();
           if(a>0){
               JOptionPane.showMessageDialog(null, "Registro Exitoso");
               logger.info("Se ingreso exitosamente al cliente: "+txt_nombre_cli.getText()+" "+txt_apellido_cli.getText());
               nuevo();
               mostrardatos("");
           }else{
               JOptionPane.showMessageDialog(null, "Error al agregar");
               logger.debug("Error, fallo al guardar");
           }
                            }else{
                                JOptionPane.showMessageDialog(null, "El RTN ya existe ingrese otro");
                                logger.debug("Error, Inserto un RTN que ya existia");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "El numero de Identidad ya existe, ingrese otro");
                            logger.debug("Error, trato de ingresar un Numero de Identidad que ya existia");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Error al agregar, el RTN debe ser de 14");
                        logger.debug("Error, trato de ingresar un RTN con menos de 14 caracteres");
                    }
                    }else{
                        JOptionPane.showMessageDialog(null,"El numero de RTN solo puede empezar con 0 o con 1");
                        logger.debug("Error, trato de ingresar un rtn que no empezaba con 0 o 1");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "El numero de identidad solo puede empezar con 0 o con 1");
                    logger.debug("Error, trato de ingresar un numero de identidad que no empezaba con 0 o 1");
                }
           }else{
               JOptionPane.showMessageDialog(null, "Error al agregar, el Num Identidad debe ser de 13");
               logger.debug("Error, agrego un numero de identidad con menos de 13 catacteres");
           }
           }
       }catch (Exception e){
           JOptionPane.showMessageDialog(null, "Error al Agregar"+e);
       }
    }
        }
       }
    }//GEN-LAST:event_btn_guardarActionPerformed

    
    private int existeUsuario(String usuario) {                                              
      
        ConexionSQL cc = new ConexionSQL();
        
        Connection cn = cc.getConnection();
        
        ResultSet rs = null;
        PreparedStatement ps = null;
        
        String sql = "SELECT count(Cli_id) FROM cliente WHERE Cli_id = ?";
    
        try {
            ps = cn.prepareStatement(sql);
            ps.setString(1, usuario);
            rs = ps.executeQuery();
            
            if(rs.next()){
                return rs.getInt(1);
            }
        } catch (Exception e) {
            return 1;
        }
        return 1;
    }
    
     private int existeId(String usuario) {                                              
      
        ConexionSQL cc = new ConexionSQL();
        
        Connection cn = cc.getConnection();
        
        ResultSet rs = null;
        PreparedStatement ps = null;
        
        String sql = "SELECT count(Cli_id) FROM cliente WHERE Num_Identidad_cliente = ?";
    
        try {
            ps = cn.prepareStatement(sql);
            ps.setString(1, usuario);
            rs = ps.executeQuery();
            
            if(rs.next()){
                return rs.getInt(1);
            }
        } catch (Exception e) {
            return 1;
        }
        return 1;
    }
     
      private int existeRTN(String usuario) {                                              
      
        ConexionSQL cc = new ConexionSQL();
        
        Connection cn = cc.getConnection();
        
        ResultSet rs = null;
        PreparedStatement ps = null;
        
        String sql = "SELECT count(Cli_id) FROM cliente WHERE rtn_cliente = ?";
    
        try {
            ps = cn.prepareStatement(sql);
            ps.setString(1, usuario);
            rs = ps.executeQuery();
            
            if(rs.next()){
                return rs.getInt(1);
            }
        } catch (Exception e) {
            return 1;
        }
        return 1;
    }
    
    private void txt_nombre_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_cliActionPerformed
void nuevo(){
txt_cli_id.setText("");
txt_nombre_cli.setText("");
txt_apellido_cli.setText("");
txt_rtn_cliente.setText("");
txt_num_id_cli.setText("");
txt_dir_cli.setText("");
}
    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
         logger.info("Limpio los campos");
    }//GEN-LAST:event_btn_nuevoActionPerformed
    String id ="";
    
    public Icon icono(String path, int width, int height){
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().
                getScaledInstance(width,height,java.awt.Image.SCALE_SMOOTH));
        return img;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mostrardatos(buscar_txt.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        logger.debug("Volvio a la ventana de Factura Venta");
        this.dispose();
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_rtn_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rtn_clienteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();
        
        if(txt_rtn_cliente.getText().length() >= 14){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_rtn_clienteKeyTyped

    private void txt_nombre_cliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_cliKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        
        if((c<'a' || c>'z')&& (c<'A' || c>'Z')) evt.consume();
        
        
        if(txt_nombre_cli.getText().length() >= 40){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_nombre_cliKeyTyped

    private void txt_apellido_cliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellido_cliKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        
        if((c<'a' || c>'z')&& (c<'A' || c>'Z')) evt.consume();
        
        if(txt_apellido_cli.getText().length() >= 40){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_apellido_cliKeyTyped

    private void txt_num_id_cliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_num_id_cliKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();
        
        
        if(txt_num_id_cli.getText().length() >= 13){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_num_id_cliKeyTyped

    private void txt_dir_cliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dir_cliKeyTyped
        // TODO add your handling code here:
        if(txt_dir_cli.getText().equals("!") || txt_dir_cli.getText().equals("~")|| txt_dir_cli.getText().equals("`")||
                   txt_dir_cli.getText().equals("@") || txt_dir_cli.getText().equals("$") || txt_dir_cli.getText().equals("%")||
                    txt_dir_cli.getText().equals("^")||txt_dir_cli.getText().equals("&")||txt_dir_cli.getText().equals("*")||
                    txt_dir_cli.getText().equals("(")||txt_dir_cli.getText().equals(")")||txt_dir_cli.getText().equals("-")||
                    txt_dir_cli.getText().equals("_")||txt_dir_cli.getText().equals("+")||txt_dir_cli.getText().equals("=")){
                    
                     evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"No se permiten caracteres especiales a parte del # y el .");
        }
        
        if(txt_dir_cli.getText().length() >= 70){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_dir_cliKeyTyped
  
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         int fila = tablaclientes.getSelectedRow();
        if(fila >= 0){
            txt_cli_id.setText(tablaclientes.getValueAt(fila, 0).toString());
            txt_rtn_cliente.setText(tablaclientes.getValueAt(fila,1).toString());
            txt_nombre_cli.setText(tablaclientes.getValueAt(fila, 2).toString());
            txt_apellido_cli.setText(tablaclientes.getValueAt(fila, 3).toString());
            txt_num_id_cli.setText(tablaclientes.getValueAt(fila, 4).toString());
            txt_dir_cli.setText(tablaclientes.getValueAt(fila, 5).toString());
            id = tablaclientes.getValueAt(fila,0).toString();
        }else{
            JOptionPane.showMessageDialog(null, "No se encontro fila ");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tablaclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclientesMouseClicked
        // TODO add your handling code here:
         int fila = tablaclientes.getSelectedRow();
        if(fila >= 0){
            txt_cli_id.setText(tablaclientes.getValueAt(fila, 0).toString());
            txt_nombre_cli.setText(tablaclientes.getValueAt(fila,1).toString());
            txt_apellido_cli.setText(tablaclientes.getValueAt(fila, 2).toString());
            txt_dir_cli.setText(tablaclientes.getValueAt(fila, 3).toString());
            txt_num_id_cli.setText(tablaclientes.getValueAt(fila, 4).toString());
            txt_rtn_cliente.setText(tablaclientes.getValueAt(fila, 5).toString());
            id = tablaclientes.getValueAt(fila,0).toString();
        }else{
            JOptionPane.showMessageDialog(null, "No se encontro fila ");
        }
    }//GEN-LAST:event_tablaclientesMouseClicked

    private void txt_rtn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rtn_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rtn_clienteActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        mostrardatos("");
        buscar_txt.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txt_num_id_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num_id_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num_id_cliActionPerformed

    private void buscar_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar_txtActionPerformed

    private void txt_cli_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cli_idKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if(c<'0' || c>'9') evt.consume();

        if(txt_cli_id.getText().length() >= 5){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_cli_idKeyTyped

    private void txt_cli_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cli_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cli_idActionPerformed

    private void txt_cli_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cli_idMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Felicidades por descubrir un easter egg del sistema de facturacion!");
    }//GEN-LAST:event_txt_cli_idMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroClientesFacEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroClientesFacEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroClientesFacEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroClientesFacEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroClientesFacEm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JTextField buscar_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTextField txt_apellido_cli;
    private javax.swing.JTextField txt_cli_id;
    private javax.swing.JTextField txt_dir_cli;
    private javax.swing.JTextField txt_nombre_cli;
    private javax.swing.JTextField txt_num_id_cli;
    private javax.swing.JTextField txt_rtn_cliente;
    // End of variables declaration//GEN-END:variables
}
