/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Venta;

import Clientes.RegistroClientes;
import Conexiones.ConexionSQL;
import Empleados.RegistrarEmpleados;
import Proveedor.frm_proveedores;
import java.awt.Toolkit;
import Clientes.datos;
import static Proveedor.frm_proveedores.idp1;
import static Proveedor.frm_proveedores.rol;
import static Proveedor.frm_proveedores.usuarios;
import inicio_sesion.modelo.SqlUsuarios;
import inicio_sesion.modelo.usuarios;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menuPrincipal;
import producto.Producto;
import org.apache.log4j.*;

/**
 *
 * @author Hector
 */
public class ModeloVenta extends javax.swing.JFrame {

    final static org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(ModeloVenta.class);

    public ModeloVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        PropertyConfigurator.configure("log4j.properties");
        mostrardatos("");
        txtcai.setText("317976-7A6111-0B419A-638143-5FA2D6-98");

        Calendar cal = Calendar.getInstance();
        String fecha;
        fecha = cal.get(Calendar.HOUR_OF_DAY) + ":" + cal.get(Calendar.MINUTE) + ":" + cal.get(Calendar.SECOND);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage());

    }

    void mostrardatos(String valor) {
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Id Detalle");
        modelo.addColumn("Producto ");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Monto");

        jTable2.setModel(modelo);
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM detalleventa";
        } else {
            sql = "SELECT * FROM detalleventa WHERE (IdDetalleVenta='" + valor + "'OR producto_id ='" + valor + "'OR cantidad ='" + valor + "'OR precio='" + valor + "')";
        }

        String[] datos = new String[4];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);

                modelo.addRow(datos);
            }
            jTable2.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdcliente1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtserie = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtcai = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBuscarCli = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        btnAddprecio = new javax.swing.JButton();
        spinCant = new javax.swing.JSpinner();
        txtcli = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtprod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtvendedor = new javax.swing.JTextField();
        txtisv = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        fechar = new rojeru_san.RSLabelFecha();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnventa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtotalapagar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        subt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        usuarios = new javax.swing.JLabel();
        rolth = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Punto de Venta \"Servicios Múltiples Cueva\"");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("\"Así abrimos, día a día, el camino del fúturo...\"");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tel: 9927-5893");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nº Factura");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        txtserie.setEditable(false);
        txtserie.setBackground(new java.awt.Color(204, 204, 204));
        txtserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserieActionPerformed(evt);
            }
        });
        txtserie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtserieKeyTyped(evt);
            }
        });
        jPanel1.add(txtserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 90, 290, 34));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("CAI");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        txtcai.setEditable(false);
        txtcai.setBackground(new java.awt.Color(204, 204, 204));
        txtcai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcaiKeyTyped(evt);
            }
        });
        jPanel1.add(txtcai, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 290, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 740, 180));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("COD: CLIENTE:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        txtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodClienteActionPerformed(evt);
            }
        });
        txtCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodClienteKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 119, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("COD: PRODUCTO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 45, -1, -1));

        txtCodProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProductoActionPerformed(evt);
            }
        });
        txtCodProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 46, 119, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("PRECIO:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        txtprecio.setEditable(false);
        jPanel2.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 119, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("CANTIDAD:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        btnBuscarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar (1).jpg"))); // NOI18N
        btnBuscarCli.setText("Buscar");
        btnBuscarCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliMouseClicked(evt);
            }
        });
        btnBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 110, -1));

        btnBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar (1).jpg"))); // NOI18N
        btnBuscarProd.setText("Buscar");
        btnBuscarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProdMouseClicked(evt);
            }
        });
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 110, -1));

        btnAddprecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.jpg"))); // NOI18N
        btnAddprecio.setText("Agregar");
        btnAddprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddprecioActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 110, -1));

        spinCant.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        spinCant.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinCantStateChanged(evt);
            }
        });
        jPanel2.add(spinCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 119, 30));

        txtcli.setEditable(false);
        jPanel2.add(txtcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 178, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("PRODUC:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        txtprod.setEditable(false);
        jPanel2.add(txtprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 180, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("ISV:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("CLIENTE:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("COD:VENDE:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        txtvendedor.setEditable(false);
        txtvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvendedorActionPerformed(evt);
            }
        });
        txtvendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvendedorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvendedorKeyTyped(evt);
            }
        });
        jPanel2.add(txtvendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 120, 30));

        txtisv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "15", "18" }));
        jPanel2.add(txtisv, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel17.setText("FECHA:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        fechar.setForeground(new java.awt.Color(0, 0, 0));
        fechar.setFormato("yyyy-MM-dd");
        jPanel2.add(fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 110, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 740, 190));

        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable2);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Facturas Detalle");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(306, 306, 306))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 740, 210));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.jpg"))); // NOI18N
        btnventa.setText("Generar Venta");
        btnventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventaActionPerformed(evt);
            }
        });
        jPanel4.add(btnventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 150, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirfactura.jpg"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasfactura.jpg"))); // NOI18N
        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton3KeyTyped(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verfacturas.jpg"))); // NOI18N
        jButton4.setText("Ver Facturas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        txtotalapagar.setEditable(false);
        txtotalapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotalapagarActionPerformed(evt);
            }
        });
        jPanel4.add(txtotalapagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 120, 35));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.jpg"))); // NOI18N
        jButton5.setText("Cancelar Factura");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Total a Pagar:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevofactura.jpg"))); // NOI18N
        jButton6.setText("Nuevo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 110, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 740, 130));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde3.jpg"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 720));

        subt.setEditable(false);
        getContentPane().add(subt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 120, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Monto x Producto");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));
        getContentPane().add(usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 700, 40, 20));
        getContentPane().add(rolth, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 30, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtotalapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotalapagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotalapagarActionPerformed

    private void btnBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBuscarCliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object[] options = {"SI", "NO"};
        int i = JOptionPane.showOptionDialog(null, "Esta seguro que desea salir del sistema?", "Seleccione una opción", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icono("/Imagenes/logo.png", 40, 40), options, options[0]);

        if (i == 0) {
            logger.debug("Salio del sistema");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void txtCodClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodClienteKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCodClienteKeyReleased

    void calularTotal() {
        /*        tpagar = 0;
         for (int i = 0; i < jTable1.getRowCount(); i++) {
         cant = Integer.parseInt(jTable1.getValueAt(i, 3).toString());
         pre = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
         tpagar = tpagar + (cant * pre);

         }
         txtotalapagar.setText("" + tpagar + "");
         */
    }


    private void btnBuscarCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliMouseClicked
        // TODO add your handling code here:
        if (txtCodCliente.getText().length() == 1 || txtCodCliente.getText().length() == 2 || txtCodCliente.getText().length() == 3) {

            try {
                String num_id_cliente = txtCodCliente.getText();

                ConexionSQL cc = new ConexionSQL();
                Connection nn = cc.getConnection();

                PreparedStatement pst = nn.prepareStatement("SELECT * FROM cliente where (Cli_id =?)");

                pst.setString(1, num_id_cliente);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    txtcli.setText(rs.getString("Nombre_Cliente"));
                    logger.debug("Se busca al cliente");
                } else {
                    JOptionPane.showMessageDialog(null, "El Cliente no se encuentra registrado");
                    logger.debug("No se encontro al cliente");
                }
            } catch (Exception e) {
            }

        } else if (txtCodCliente.getText().length() == 13) {
            try {
                String num_id_cliente = txtCodCliente.getText();

                ConexionSQL cc = new ConexionSQL();
                Connection nn = cc.getConnection();

                PreparedStatement pst = nn.prepareStatement("SELECT * FROM cliente where (Num_Identidad_cliente =?)");

                pst.setString(1, num_id_cliente);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    txtcli.setText(rs.getString("Nombre_Cliente"));
                    logger.debug("Se busca al cliente");
                } else {
                    JOptionPane.showMessageDialog(null, "El Cliente no se encuentra registrado");
                    logger.debug("No se encontro al cliente");
                }
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_btnBuscarCliMouseClicked

    private void btnBuscarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProdMouseClicked
        // TODO add your handling code here:
        try {
            int nombre = Integer.parseInt(txtCodProducto.getText());

            ConexionSQL cc = new ConexionSQL();
            Connection nn = cc.getConnection();

            PreparedStatement pst = nn.prepareStatement("Select * from productos where IdProducto =?");

            pst.setInt(1, nombre);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                txtprod.setText(rs.getString("Nombre"));
                txtprecio.setText(rs.getString("Precio"));
                logger.debug("Se encuentra el producto");
            } else {
                JOptionPane.showMessageDialog(null, "El Producto no se encuentra registrado");
                logger.debug("No se encontro el producto");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscarProdMouseClicked

    private void txtvendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvendedorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvendedorKeyPressed

    private void spinCantStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinCantStateChanged

        double role = Integer.parseInt(spinCant.getValue().toString());
        double prec = Integer.parseInt(txtprecio.getText());

        double pre = Integer.parseInt(txtprecio.getText().toString());
        double princi = Integer.parseInt(txtisv.getSelectedItem().toString());

        double secon = princi * 0.01;
        double terc = secon * pre;
        double to = terc + pre;

        double tot = role * to;

        subt.setText(String.valueOf(Math.round(tot)));


    }//GEN-LAST:event_spinCantStateChanged

    private void btnAddprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddprecioActionPerformed
        // TODO add your handling code here:
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        String sql;
        String cap1 = "";

        sql = "SELECT * FROM `venta_estado` WHERE `nom_usuario` = '" + usuarios.getText() + "'";
        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cap1 = rs.getString("guardar");

            }
            if (cap1.equals("activo")) {

                if (txtCodProducto.getText().equals("") || txtCodProducto.getText().equals("") || txtprecio.getText().equals("") || subt.getText().equals("")
                        || txtvendedor.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Todos los campos tienen que ir llenos");
                    logger.debug("Los campos no deben ir vacios");
                } else {
                    if (spinCant.getValue().toString().startsWith("1") || spinCant.getValue().toString().startsWith("2") || spinCant.getValue().toString().startsWith("3") || spinCant.getValue().toString().startsWith("4")
                            || spinCant.getValue().toString().startsWith("5") || spinCant.getValue().toString().startsWith("6") || spinCant.getValue().toString().startsWith("7") || spinCant.getValue().toString().startsWith("8")
                            || spinCant.getValue().toString().startsWith("9")) {
                        DefaultTableModel model = new DefaultTableModel();

                        model = (DefaultTableModel) jTable2.getModel();

                        model.addRow(new Object[]{
                            txtserie.getText(),
                            txtCodProducto.getText(),
                            spinCant.getValue().toString(),
                            txtprecio.getText(),
                            subt.getText()

                        });

                        txtCodProducto.setText("");

                        txtprod.setText("");
                        logger.debug("agrega el producto a la factura");
                    } else {
                        JOptionPane.showMessageDialog(null, "La cantidad a llevar no puede ser 0");
                        logger.debug("la cantidad a llevar no puede ser 0");
                    }
                }
                double sum = 0;

                for (int i = 0; i < jTable2.getRowCount(); i++) {

                    sum = sum + Integer.parseInt(jTable2.getValueAt(i, 4).toString());

                }
                Math.round(sum);

                txtotalapagar.setText(String.valueOf(sum));

                spinCant.setValue(0);

            } else {
                JOptionPane.showMessageDialog(null, "No tiene permiso para ejecutar esta operacion");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No tiene permiso para ejecutar esta operacion");
        }


    }//GEN-LAST:event_btnAddprecioActionPerformed
    void limpiar() {
        txtserie.setText("");
        txtCodCliente.setText("");

        txtisv.setSelectedItem("0");
        txtcai.setText("317976-7A6111-0B419A-638143-5FA2D6-98");
        subt.setText("");
        spinCant.setValue("");
        txtprecio.setText("");
        txtcli.setText("");
        txtprod.setText("");

        txtisv.setSelectedItem("0");
        txtcli.setText("");
        txtprecio.setText("");
        txtotalapagar.setText("");
    }
    private void btnventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventaActionPerformed

        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();

        String sql;
        String cap1 = "";

        sql = "SELECT * FROM `venta_estado` WHERE `nom_usuario` = '" + usuarios.getText() + "'";
        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cap1 = rs.getString("guardar");

            }
            if (cap1.equals("activo")) {

                try {

                    PreparedStatement pst = cn.prepareStatement("INSERT INTO `ventas` (`IdVentas`, `Cliente_IdCliente`, `Vendedor_IdVendedor`, `cai`, `monto`, `isv`,`fecha_registro`) VALUES (NULL, ?, ?, ?, ?, ?, ?)");

                    pst.setString(1, txtCodCliente.getText());
                    pst.setString(2, txtvendedor.getText());
                    pst.setString(3, txtcai.getText());
                    pst.setString(4, txtotalapagar.getText());
                    pst.setString(5, txtisv.getSelectedItem().toString());
                    pst.setString(6, fechar.getFecha());

                    int a = pst.executeUpdate();
                    if (a > 0) {
                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                        logger.debug("Realizo una venta exitosa");
                        limpiar();
                        mostrardatos("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al agregar");
                        logger.debug("Error al momento de registrar la venta");
                    }

                } catch (Exception e) {

                }

                txtcai.setText("317976-7A6111-0B419A-638143-5FA2D6-98");
                double sum = 0;

                for (int i = 0; i < jTable2.getRowCount(); i++) {

                    sum = sum + Integer.parseInt(jTable2.getValueAt(i, 5).toString());

                }
                Math.round(sum);
                txtotalapagar.setText(Integer.toString((int) sum));

            } else {
                JOptionPane.showMessageDialog(null, "No tiene permiso para ejecutar esta operacion");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No tiene permiso para ejecutar esta operacion");
        }


    }//GEN-LAST:event_btnventaActionPerformed

    void validacionVenta(String usuario) {
        String cap1 = "";
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        String sql;

        sql = "SELECT * FROM `compra_estado` WHERE `nom_usuario` = '" + usuario + "'";

        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cap1 = rs.getString("mirar");

            }
            if (cap1.equals("inactivo")) {
                menuPrincipal.registrarVenta.setVisible(false);
                menuPrincipal.jLabel3.setVisible(false);
            } else {
                menuPrincipal.registrarVenta.setVisible(true);
                menuPrincipal.jLabel3.setVisible(true);
            }

        } catch (Exception e) {

        }

    }

    void validacionProductos(String usuario) {

        String cap1 = "";
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        String sql;

        sql = "SELECT * FROM `producto_estado` WHERE `nom_usuario` = '" + usuario + "'";

        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cap1 = rs.getString("mirar");

            }
            if (cap1.equals("inactivo")) {
                menuPrincipal.jButton7.setVisible(false);
                menuPrincipal.jLabel7.setVisible(false);
            } else {
                menuPrincipal.jButton7.setVisible(true);
                menuPrincipal.jLabel7.setVisible(true);
            }

        } catch (Exception e) {

        }
    }

    void validacionCompra(String usuario) {
        String cap1 = "";
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        String sql;

        sql = "SELECT * FROM `compra_estado` WHERE `nom_usuario` = '" + usuario + "'";

        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cap1 = rs.getString("mirar");

            }
            if (cap1.equals("inactivo")) {
                menuPrincipal.jButton1.setVisible(false);
                menuPrincipal.jLabel1.setVisible(false);
            } else {
                menuPrincipal.jButton1.setVisible(true);
                menuPrincipal.jLabel1.setVisible(true);
            }

        } catch (Exception e) {

        }
    }

    void validacionProveedor(String usuario) {
        String cap1 = "";
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        String sql;

        sql = "SELECT * FROM `proveedor_estado` WHERE `nom_usuario` = '" + usuario + "'";

        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cap1 = rs.getString("mirar");

            }
            if (cap1.equals("inactivo")) {
                menuPrincipal.jButton2.setVisible(false);
                menuPrincipal.jLabel8.setVisible(false);
            } else {
                menuPrincipal.jButton2.setVisible(true);
                menuPrincipal.jLabel8.setVisible(true);
            }

        } catch (Exception e) {

        }

    }

    void validacionCliente(String usuario) {

        String cap1 = "";
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        String sql;

        sql = "SELECT * FROM `cliente_estado` WHERE `nom_usuario` = '" + usuario + "'";

        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cap1 = rs.getString("mirar");

            }
            if (cap1.equals("inactivo")) {
                menuPrincipal.registroEmpleado.setVisible(false);
                menuPrincipal.jLabel5.setVisible(false);
            } else {
                menuPrincipal.registroEmpleado.setVisible(true);
                menuPrincipal.jLabel5.setVisible(true);
            }

        } catch (Exception e) {

        }

    }

    void validacion(String usuario) {
        String cap1 = "";
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        String sql;

        sql = "SELECT * FROM `vendedor_estado` WHERE `nom_usuario` = '" + usuario + "'";

        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cap1 = rs.getString("mirar");

            }
            if (cap1.equals("inactivo")) {
                menuPrincipal.registroEmpleados1.setVisible(false);
                menuPrincipal.jLabel4.setVisible(false);
            } else {
                menuPrincipal.registroEmpleados1.setVisible(true);
                menuPrincipal.jLabel4.setVisible(true);
            }

        } catch (Exception e) {

        }

    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SqlUsuarios modSql = new SqlUsuarios();
        usuarios mod = new usuarios();

        Object[] options = {"SI", "NO"};
        int i = JOptionPane.showOptionDialog(null, "Esta seguro que desea volver al menu principal?", "Seleccione una opción", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icono("/Imagenes/logo.png", 40, 40), options, options[0]);

        if (i == 0) {
            logger.debug("vuelve al menu principal");
            
            mod.setId_tipo(1);

            menuPrincipal mp = new menuPrincipal(mod);
            mp.setVisible(true);

            validacion(usuarios.getText());
            validacionCliente(usuarios.getText());
            validacionProveedor(usuarios.getText());
            validacionCompra(usuarios.getText());
            validacionProductos(usuarios.getText());
            validacionVenta(usuarios.getText());
            this.dispose();

        };
        menuPrincipal.nombre.setText(usuarios.getText());
        menuPrincipal.rol.setText(rolth.getText());
        menuPrincipal.idv.setText(txtvendedor.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCodClienteActionPerformed

    private void txtCodClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodClienteKeyPressed

    private void txtCodClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodClienteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (txtCodCliente.getText().length() >= 13) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodClienteKeyTyped

    private void txtCodProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (txtCodProducto.getText().length() >= 5) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodProductoKeyTyped

    private void txtvendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvendedorKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (txtvendedor.getText().length() >= 5) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtvendedorKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        logger.debug("Entra a ver las facturas guardadas");
        VerFacturaVenta ver = new VerFacturaVenta();
        ver.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    public Icon icono(String path, int width, int height) {
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().
                getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH));
        return img;
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Object[] options = {"SI", "NO"};
        int i = JOptionPane.showOptionDialog(null, "Esta seguro que desea eliminar el registro?", "Seleccione una opcion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icono("/Imagenes/logo.png", 40, 40), options, options[0]);
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        int fila = jTable2.getSelectedRow();
        String cod = "";
        cod = jTable2.getValueAt(fila, 1).toString();

        txtotalapagar.setText("");
        txtprecio.setText("");

        txtcli.setText("");

        if (i == 0) {
            try {
                PreparedStatement pst = cn.prepareStatement("DELETE FROM detalleventa WHERE IdDetalleventa= '" + cod + "'");
                pst.executeUpdate();
                logger.debug("Factura cancelada con exito");
                mostrardatos("");// TODO add your handling code here:
                JOptionPane.showMessageDialog(null, "Se a eliminado con exito");

            } catch (Exception e) {
            }

            txtcai.setText("317976-7A6111-0B419A-638143-5FA2D6-98");

        }
        limpiar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCodProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProductoActionPerformed

    private void txtvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvendedorActionPerformed

    private void txtserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserieActionPerformed

    private void txtserieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserieKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtserieKeyTyped

    private void txtcaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaiKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaiKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        int fila = jTable2.getSelectedRow();
        String cod = "";
        cod = jTable2.getValueAt(fila, 1).toString();

        txtotalapagar.setText("");
        txtprecio.setText("");

        txtcli.setText("");

        try {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM detalleventa WHERE IdDetalleventa= '" + cod + "'");
            logger.debug("Limpia los campos");
            pst.executeUpdate();

            mostrardatos("");// TODO add your handling code here:

            Calendar cal = Calendar.getInstance();
            String fecha;
            fecha = cal.get(Calendar.YEAR) + "-" + cal.get(Calendar.MONTH) + "-" + cal.get(Calendar.DATE) + " " + cal.get(Calendar.HOUR_OF_DAY) + ":" + cal.get(Calendar.MINUTE) + ":" + cal.get(Calendar.SECOND);

        } catch (Exception e) {
        }

        txtcai.setText("317976-7A6111-0B419A-638143-5FA2D6-98");

        limpiar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeloVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeloVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeloVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeloVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModeloVenta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddprecio;
    private javax.swing.JButton btnBuscarCli;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnventa;
    private rojeru_san.RSLabelFecha fechar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel rolth;
    private javax.swing.JSpinner spinCant;
    private javax.swing.JTextField subt;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtIdcliente1;
    private javax.swing.JTextField txtcai;
    private javax.swing.JTextField txtcli;
    private javax.swing.JComboBox txtisv;
    private javax.swing.JTextField txtotalapagar;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprod;
    private javax.swing.JTextField txtserie;
    public static javax.swing.JTextField txtvendedor;
    public static javax.swing.JLabel usuarios;
    // End of variables declaration//GEN-END:variables

}
