/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedor;

import Clientes.RegistroClientes;
import Clientes.datos;
import Conexiones.ConexionSQL;
import Empleados.RegistrarEmpleados;

import contactos.contacto_proveedor.ContactoP;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menuPrincipal;
import producto.Producto;

/**
 *
 * @author Hector
 */
public class frm_proveedores extends javax.swing.JFrame {

    /*
     * Creates new form frm_proveedores
     */
    Connection conectar = null;

    public frm_proveedores() {
        initComponents();

        mostrardatos("");
        bloquear();
        limpiar();
        this.setLocationRelativeTo(null);
    }

    void mostrardatos(String valor) {
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID Empresa");
        modelo.addColumn("Nombre Empresa");
        modelo.addColumn("Direccion");
        modelo.addColumn("RTN");

        tabla1.setModel(modelo);
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM proveedor";
        } else {
            sql = "SELECT * FROM proveedor WHERE (Empresa_id='" + valor + "'OR Nombre_Empresa='" + valor + "'OR Direccion_Empresa='" + valor + "'OR rtn_empresa='" + valor + "')";
        }
        String[] datos = new String[4];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);

                modelo.addRow(datos);

            }
            tabla1.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(datos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void limpiar() {
        Jtf_Id.setText("");
        Jtf_Nombre_Empresa.setText("");
        jtf_Rtn.setText("");
        Jtf_Direccion.setText("");
    }

    void desbloquear() {
        Jtf_Id.setEnabled(true);
        Jtf_Nombre_Empresa.setEnabled(true);
        jtf_Rtn.setEnabled(true);
        Jtf_Direccion.setEnabled(true);

        Jbt_Guardar.setEnabled(true);
        jtf_nuevo.setEnabled(true);
        jtf_editar.setEnabled(true);
        Jbt_Eliminar.setEnabled(true);
        jtf_salir.setEnabled(true);
    }

    void bloquear() {
        Jtf_Id.setEnabled(false);
        Jtf_Nombre_Empresa.setEnabled(false);
        jtf_Rtn.setEnabled(false);
        Jtf_Direccion.setEnabled(false);

        Jbt_Guardar.setEnabled(false);
        jtf_nuevo.setEnabled(true);
        jtf_editar.setEnabled(false);
        Jbt_Eliminar.setEnabled(false);
        jtf_salir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Jtf_Id = new javax.swing.JTextField();
        Jbt_Guardar = new javax.swing.JButton();
        Jtf_Nombre_Empresa = new javax.swing.JTextField();
        Jtf_Direccion = new javax.swing.JTextField();
        jtf_Rtn = new javax.swing.JTextField();
        Jbt_Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jtf_editar = new javax.swing.JButton();
        jtf_nuevo = new javax.swing.JButton();
        jtf_salir = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buscar_txt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        contacto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 844));
        setMinimumSize(new java.awt.Dimension(980, 573));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Id Proveedor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jLabel3.setText("Nombre Empresa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, 19));

        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jLabel5.setText("RTN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Jtf_Nombre_Empresa, org.jdesktop.beansbinding.ObjectProperty.create(), Jtf_Id, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        Jtf_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_IdActionPerformed(evt);
            }
        });
        Jtf_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_IdKeyTyped(evt);
            }
        });
        getContentPane().add(Jtf_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 152, 27));

        Jbt_Guardar.setBackground(new java.awt.Color(0, 0, 153));
        Jbt_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Jbt_Guardar.setText("GUARDAR");
        Jbt_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbt_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbt_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 90, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtf_Rtn, org.jdesktop.beansbinding.ObjectProperty.create(), Jtf_Nombre_Empresa, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        Jtf_Nombre_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_Nombre_EmpresaActionPerformed(evt);
            }
        });
        Jtf_Nombre_Empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_Nombre_EmpresaKeyTyped(evt);
            }
        });
        getContentPane().add(Jtf_Nombre_Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 152, 30));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Jbt_Guardar, org.jdesktop.beansbinding.ObjectProperty.create(), Jtf_Direccion, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        Jtf_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_DireccionKeyTyped(evt);
            }
        });
        getContentPane().add(Jtf_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 156, 70));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Jtf_Direccion, org.jdesktop.beansbinding.ObjectProperty.create(), jtf_Rtn, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        jtf_Rtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_RtnKeyTyped(evt);
            }
        });
        getContentPane().add(jtf_Rtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 156, 31));

        Jbt_Eliminar.setBackground(new java.awt.Color(0, 0, 153));
        Jbt_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Jbt_Eliminar.setText("ELIMINAR");
        Jbt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbt_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbt_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 90, -1));

        tabla1.setForeground(new java.awt.Color(0, 0, 153));
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla1.setColumnSelectionAllowed(true);
        tabla1.setComponentPopupMenu(jPopupMenu1);
        tabla1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 565, 186));

        jtf_editar.setBackground(new java.awt.Color(0, 0, 153));
        jtf_editar.setForeground(new java.awt.Color(255, 255, 255));
        jtf_editar.setText("EDITAR");
        jtf_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_editarActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 90, -1));

        jtf_nuevo.setBackground(new java.awt.Color(0, 0, 153));
        jtf_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jtf_nuevo.setText("NUEVO");
        jtf_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 90, -1));

        jtf_salir.setBackground(new java.awt.Color(204, 204, 204));
        jtf_salir.setForeground(new java.awt.Color(255, 0, 0));
        jtf_salir.setText("SALIR");
        jtf_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 821, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("INICIO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 153));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("REGISTRAR EMPLEADOS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 153));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("REGISTRAR CLIENTES");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 153));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("REGISTRAR FACTURA VENTA");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 153));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("REGISTRAR FACTURA COMPRA");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));
        getContentPane().add(buscar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 140, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ATRÁS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 90, -1));

        contacto.setBackground(new java.awt.Color(0, 0, 153));
        contacto.setForeground(new java.awt.Color(255, 255, 255));
        contacto.setText("CONTACTO");
        contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactoActionPerformed(evt);
            }
        });
        getContentPane().add(contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Registrar Productos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jButton9.setBackground(new java.awt.Color(0, 0, 153));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Mostrar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jButton10.setBackground(new java.awt.Color(0, 153, 204));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("SALIR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("REGISTRO DE PROVEEDORES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde3.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(980, 573));
        jLabel1.setMinimumSize(new java.awt.Dimension(980, 573));
        jLabel1.setPreferredSize(new java.awt.Dimension(980, 573));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int existeUsuario(String usuario) {

        ConexionSQL cc = new ConexionSQL();

        Connection cn = cc.getConnection();

        ResultSet rs = null;
        PreparedStatement ps = null;

        String sql = "SELECT count(Empresa_id) FROM proveedor WHERE Empresa_id = ?";

        try {
            ps = cn.prepareStatement(sql);
            ps.setString(1, usuario);
            rs = ps.executeQuery();

            if (rs.next()) {
                return rs.getInt(1);
            }
        } catch (Exception e) {
            return 1;
        }
        return 1;
    }
    String id = "";
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:4

        int fila = tabla1.getSelectedRow();

        if (fila >= 0) {
            Jtf_Id.setText(tabla1.getValueAt(fila, 0).toString());
            Jtf_Nombre_Empresa.setText(tabla1.getValueAt(fila, 1).toString());
            jtf_Rtn.setText(tabla1.getValueAt(fila, 2).toString());
            Jtf_Direccion.setText(tabla1.getValueAt(fila, 3).toString());
            id = tabla1.getValueAt(fila, 0).toString();

        } else {
            JOptionPane.showMessageDialog(null, "No se encontro fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactoActionPerformed
        // TODO add your handling code here:

        ContactoP contacto = new ContactoP();
        contacto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_contactoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menuPrincipal menu = new menuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrardatos(buscar_txt.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtf_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jtf_salirActionPerformed
    void nuevo() {
        this.Jtf_Id.setText("");
        this.Jtf_Nombre_Empresa.setText("");
        this.jtf_Rtn.setText("");
        this.Jtf_Direccion.setText("");

        this.Jtf_Id.grabFocus();
    }
    private void jtf_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
        desbloquear();
    }//GEN-LAST:event_jtf_nuevoActionPerformed

    private void jtf_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_editarActionPerformed
        // TODO add your handling code here:
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();

        if (Jtf_Id.getText().equals("") || Jtf_Nombre_Empresa.getText().equals("") || jtf_Rtn.getText().equals("")
                || Jtf_Direccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos que estan vacios. No pueden quedar asi ");
        } else {

            try {
                if (jtf_Rtn.getText().length() >= 14) {
                    PreparedStatement pst = cn.prepareStatement("UPDATE proveedor SET Empresa_id='" + Jtf_Id.getText() + "',Nombre_Empresa='" + Jtf_Nombre_Empresa.getText() + "',Direccion_Empresa='" + Jtf_Direccion.getText() + "',rtn_empresa='" + jtf_Rtn.getText() + "'WHERE Empresa_id='" + id + "'");
                    id = Jtf_Id.getText();
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Se modifico con exito");
                    mostrardatos("");
                } else {
                    JOptionPane.showMessageDialog(null, "El RTN debe ser de 14 caracteres");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jtf_editarActionPerformed

    private void Jbt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbt_EliminarActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Esta segura que desea borrar?");
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();

        int fila = tabla1.getSelectedRow();
        String cod = "";
        cod = tabla1.getValueAt(fila, 0).toString();
        if (i == 0) {
            try {
                PreparedStatement pst = cn.prepareStatement("DELETE FROM proveedor WHERE Empresa_id='" + cod + "'");
                pst.executeUpdate();
                mostrardatos("");
                int a = pst.executeUpdate();
                if (a > 0) {
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar");
                } else {
                    JOptionPane.showMessageDialog(null, "Eliminacion exitosa");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar, el proveedor tiene facturas registradas");
            }
            bloquear();
            limpiar();
        }
    }//GEN-LAST:event_Jbt_EliminarActionPerformed

    private void jtf_RtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_RtnKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (jtf_Rtn.getText().length() >= 14) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jtf_RtnKeyTyped

    private void Jtf_DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_DireccionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }

        if (Jtf_Direccion.getText().length() >= 60) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_Jtf_DireccionKeyTyped

    private void Jtf_Nombre_EmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_Nombre_EmpresaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        if (Jtf_Nombre_Empresa.getText().length() >= 25) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_Jtf_Nombre_EmpresaKeyTyped

    private void Jtf_Nombre_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_Nombre_EmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_Nombre_EmpresaActionPerformed

    private void Jbt_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbt_GuardarActionPerformed
        // TODO add your handling code here:
        ConexionSQL cc = new ConexionSQL();

        Connection cn = cc.getConnection();

        if (Jtf_Id.getText().equals("") || Jtf_Nombre_Empresa.getText().equals("") || jtf_Rtn.getText().equals("")
                || Jtf_Direccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos que estan vacios. No pueden quedar asi ");
        } else {

            try {

                if (existeUsuario(Jtf_Id.getText()) == 0) {
                    if (jtf_Rtn.getText().length() >= 14) {
                        if (Jtf_Nombre_Empresa.getText().length() >= 3) {
                            if (jtf_Rtn.getText().startsWith("0") || jtf_Rtn.getText().startsWith("1")) {

                                PreparedStatement pst = cn.prepareStatement("INSERT INTO proveedor(Empresa_id,Nombre_Empresa,Direccion_Empresa,rtn_empresa) values(?,?,?,?)");
                                pst.setString(1, Jtf_Id.getText());
                                pst.setString(2, Jtf_Nombre_Empresa.getText());
                                pst.setString(3, Jtf_Direccion.getText());
                                pst.setString(4, jtf_Rtn.getText());

                                int a = pst.executeUpdate();

                                if (a > 0) {
                                    JOptionPane.showMessageDialog(null, "Registro Guardado con Exito");
                                    nuevo();
                                    mostrardatos("");
                                } else {
                                    JOptionPane.showMessageDialog(null, "Error al Agregar Registro");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "El RTN debe empezar con 0 o 1");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "El Nombre debe tener al menos 3 caracteres");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El RTN debe ser de 14");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                }
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_Jbt_GuardarActionPerformed

    private void Jtf_IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_IdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (Jtf_Id.getText().length() >= 5) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_Jtf_IdKeyTyped

    private void Jtf_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_IdActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        // TODO add your handling code here:

        int fila = tabla1.getSelectedRow();

        if (fila >= 0) {
            Jtf_Id.setText(tabla1.getValueAt(fila, 0).toString());
            Jtf_Nombre_Empresa.setText(tabla1.getValueAt(fila, 1).toString());
            Jtf_Direccion.setText(tabla1.getValueAt(fila, 2).toString());
            jtf_Rtn.setText(tabla1.getValueAt(fila, 3).toString());
            id = tabla1.getValueAt(fila, 0).toString();

        } else {
            JOptionPane.showMessageDialog(null, "No se encontro fila");
        }
    }//GEN-LAST:event_tabla1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        menuPrincipal menu = new menuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        RegistrarEmpleados re = new RegistrarEmpleados();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        RegistroClientes rc = new RegistroClientes();
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        mostrardatos("");
        buscar_txt.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbt_Eliminar;
    private javax.swing.JButton Jbt_Guardar;
    private javax.swing.JTextField Jtf_Direccion;
    private javax.swing.JTextField Jtf_Id;
    private javax.swing.JTextField Jtf_Nombre_Empresa;
    private javax.swing.JTextField buscar_txt;
    private javax.swing.JButton contacto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtf_Rtn;
    private javax.swing.JButton jtf_editar;
    private javax.swing.JButton jtf_nuevo;
    private javax.swing.JButton jtf_salir;
    private javax.swing.JTable tabla1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
