/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import Conexiones.ConexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.log4j.Level;
import org.apache.log4j.PropertyConfigurator;

/**
 *
 * @author Luis Cueva
 */
public class permisos extends javax.swing.JFrame {

    /**
     * Creates new form permisos
     */
    public permisos() {
        initComponents();
        PropertyConfigurator.configure("log4j.properties");
        mostrartipoproducto();
        mostrarusuario();
        mostrarCliEstado();
        this.setLocationRelativeTo(null);
    }
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
    void mostrarusuario(){
     
        
        
       String sql="SELECT * FROM `vendedor` WHERE Vendedor_id != 1";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                usuariobox.addItem(rs.getString("usuario"));
            }
        } catch (Exception e) {
            //Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    void mostrarCliEstado(){
       
        
        
       String sql="SELECT * FROM `estado`";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                modificarClibox.addItem(rs.getString("descripcion_estado"));
                eliminarCliBox.addItem(rs.getString("descripcion_estado"));
                guardarCliBox.addItem(rs.getString("descripcion_estado"));
                entrarboxcli.addItem(rs.getString("descripcion_estado"));
                
                modificarProvbox.addItem(rs.getString("descripcion_estado"));
                eliminarProvBox2.addItem(rs.getString("descripcion_estado"));
                guardarProvBox.addItem(rs.getString("descripcion_estado"));
                entrarboxprov.addItem(rs.getString("descripcion_estado"));
                
                
                modificarProdubox.addItem(rs.getString("descripcion_estado"));
                eliminarProduBox.addItem(rs.getString("descripcion_estado"));
                guardarProduBox.addItem(rs.getString("descripcion_estado"));
                entrarboxprodu.addItem(rs.getString("descripcion_estado"));
                
                
                guardarCompraBox.addItem(rs.getString("descripcion_estado"));
                entrarboxcompra.addItem(rs.getString("descripcion_estado"));
                
                
                guardarVentaBox.addItem(rs.getString("descripcion_estado"));
                entrarboxventa.addItem(rs.getString("descripcion_estado"));
            }
        } catch (Exception e) {
            //Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void mostrartipoproducto(){
       
        
        
       String sql="SELECT * FROM `estado`";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                categoriabox.addItem(rs.getString("descripcion_estado"));
                eliminarbox.addItem(rs.getString("descripcion_estado"));
                guardarbox.addItem(rs.getString("descripcion_estado"));
                entrarbox.addItem(rs.getString("descripcion_estado"));
            }
        } catch (Exception e) {
            //Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        usuariobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        categoriabox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eliminarbox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        guardarbox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        entrarbox = new javax.swing.JComboBox<>();
        aplicarbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        modificarClibox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        eliminarCliBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        guardarCliBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        entrarboxcli = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        modificarProvbox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        eliminarProduBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        guardarProvBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        entrarboxprov = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        modificarProdubox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        eliminarProvBox2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        guardarProduBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        entrarboxprodu = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        guardarCompraBox = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        entrarboxcompra = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        guardarVentaBox = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        entrarboxventa = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        desbloqueo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));

        usuariobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioboxActionPerformed(evt);
            }
        });
        getContentPane().add(usuariobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro Empleados: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, -1, -1));

        categoriabox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaboxActionPerformed(evt);
            }
        });
        getContentPane().add(categoriabox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 71, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Editar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eliminar:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 102, -1, -1));

        eliminarbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarboxActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 99, 80, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Guardar: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        getContentPane().add(guardarbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 80, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Entrar:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        getContentPane().add(entrarbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 80, -1));

        aplicarbtn.setText("Aplicar");
        aplicarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(aplicarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Factura Compra:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Editar: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        modificarClibox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarCliboxActionPerformed(evt);
            }
        });
        getContentPane().add(modificarClibox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 70, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Eliminar:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        getContentPane().add(eliminarCliBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 80, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Guardar: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        getContentPane().add(guardarCliBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 80, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Entrar:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        getContentPane().add(entrarboxcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 80, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Registro Clientes: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 10));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Editar: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        modificarProvbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProvboxActionPerformed(evt);
            }
        });
        getContentPane().add(modificarProvbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 70, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Eliminar:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        getContentPane().add(eliminarProduBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 80, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Guardar: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        getContentPane().add(guardarProvBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 80, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Entrar:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        getContentPane().add(entrarboxprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 80, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Registro Proveedores: ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Editar: ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        modificarProdubox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProduboxActionPerformed(evt);
            }
        });
        getContentPane().add(modificarProdubox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 70, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Eliminar:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        getContentPane().add(eliminarProvBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 80, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Guardar: ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        getContentPane().add(guardarProduBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 80, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Entrar:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        getContentPane().add(entrarboxprodu, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 80, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Registro Productos: ");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Guardar: ");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        getContentPane().add(guardarCompraBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 80, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Entrar:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        getContentPane().add(entrarboxcompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 80, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Factura Venta:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Guardar: ");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        getContentPane().add(guardarVentaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 80, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Entrar:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        getContentPane().add(entrarboxventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 80, -1));

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        jButton2.setText("Aplicar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        desbloqueo.setText("Desbloquear usuario");
        desbloqueo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desbloqueoMouseClicked(evt);
            }
        });
        getContentPane().add(desbloqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 150, -1));

        jButton3.setText("Aplicar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        jButton4.setText("Aplicar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        jButton5.setText("Aplicar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Abstract_sky_blue-2016_Vector_Design_HD_Wallpaper_1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 550));

        jButton6.setText("Aplicar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarboxActionPerformed

    private void categoriaboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_categoriaboxActionPerformed

    private void aplicarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarbtnActionPerformed
        // TODO add your handling code here:
        
         
         try{
        PreparedStatement pst = cn.prepareStatement("UPDATE `compra_estado` SET `guardar`='"+guardarVentaBox.getSelectedItem().toString()+
                "',`mirar`='"+entrarboxventa.getSelectedItem().toString()+"',`nom_usuario`='"+usuariobox.getSelectedItem().toString()+
                "' WHERE nom_usuario='"+ usuariobox.getSelectedItem().toString()+"'");
 
            int a = pst.executeUpdate();
            if (a > 0) {
                JOptionPane.showMessageDialog(null, "Modificacion exitosa permisos Compra para: "+usuariobox.getSelectedItem().toString());
                //logger.info("se registra exitosamente la factura");
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar: ");
                //logger.info("hubo error al agregar la factura");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_aplicarbtnActionPerformed

    private void usuarioboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioboxActionPerformed

    private void modificarCliboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarCliboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarCliboxActionPerformed

    private void modificarProvboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProvboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProvboxActionPerformed

    private void modificarProduboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProduboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProduboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try{
            PreparedStatement pst = cn.prepareStatement("UPDATE `vendedor_estado` SET `modificar`='"+categoriabox.getSelectedItem().toString()+"',`eliminar`='"+eliminarbox.getSelectedItem().toString()+"',`guardar`='"+guardarbox.getSelectedItem().toString()+"',`mirar`='"+entrarbox.getSelectedItem().toString()+"',`nom_usuario`='"+usuariobox.getSelectedItem().toString()+"' WHERE nom_usuario='"+usuariobox.getSelectedItem().toString()+"'");
            
            int a = pst.executeUpdate();
            if (a > 0) {
                JOptionPane.showMessageDialog(null, "Modificacion exitosa permisos Vendedor para: "+usuariobox.getSelectedItem().toString());
                //logger.info("se registra exitosamente la factura");
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
                //logger.info("hubo error al agregar la factura");
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try{
        PreparedStatement pst = cn.prepareStatement("UPDATE `cliente_estado` SET `modificar`='"+modificarClibox.getSelectedItem().toString()+"',`eliminar`='"+eliminarCliBox.getSelectedItem().toString()+"',`guardar`='"+guardarCliBox.getSelectedItem().toString()+"',`mirar`='"+entrarboxcli.getSelectedItem().toString()+"',`nom_usuario`='"+usuariobox.getSelectedItem().toString()+"' WHERE nom_usuario='"+usuariobox.getSelectedItem().toString()+"'");
           
            
            int a = pst.executeUpdate();
            if (a > 0) {
                JOptionPane.showMessageDialog(null, "Modificacion exitosa permisos Cliente para: "+usuariobox.getSelectedItem().toString());
                //logger.info("se registra exitosamente la factura");
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar");
                //logger.info("hubo error al agregar la factura");
            }
        }catch(Exception e){
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        PreparedStatement pst = cn.prepareStatement("UPDATE `proveedor_estado` SET `modificar`='"+ 
                modificarProvbox.getSelectedItem().toString()+"',`eliminar`='"+eliminarProvBox2.getSelectedItem().toString()+
                "',`guardar`='"+guardarProvBox.getSelectedItem().toString()+
                "',`mirar`='"+entrarboxprov.getSelectedItem().toString()+"',`nom_usuario`='"+usuariobox.getSelectedItem().toString()+"' WHERE nom_usuario='"+usuariobox.getSelectedItem().toString()+"'");

            
            int a = pst.executeUpdate();
            if (a > 0) {
                JOptionPane.showMessageDialog(null, "Modificacion exitosa permisos Proveedor para: "+usuariobox.getSelectedItem().toString());
                //logger.info("se registra exitosamente la factura");
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
                //logger.info("hubo error al agregar la factura");
            }
        }catch(Exception e){
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        try{
        PreparedStatement pst = cn.prepareStatement("UPDATE `producto_estado` SET `modificar`='"+ 
               modificarProdubox.getSelectedItem().toString()+"',`eliminar`='"+eliminarProduBox.getSelectedItem().toString()+
                "',`guardar`='"+guardarProduBox.getSelectedItem().toString()+
                "',`mirar`='"+entrarboxprodu.getSelectedItem().toString()+"',`nom_usuario`='"+usuariobox.getSelectedItem().toString()+
                "' WHERE nom_usuario='"+usuariobox.getSelectedItem().toString()+"'");
           
            int a = pst.executeUpdate();
            if (a > 0) {
                JOptionPane.showMessageDialog(null, "Modificacion exitosa permisos Producto para: "+usuariobox.getSelectedItem().toString());
                //logger.info("se registra exitosamente la factura");
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
                //logger.info("hubo error al agregar la factura");
            }
        }catch(Exception e){
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        
         try{
        PreparedStatement pst = cn.prepareStatement("UPDATE `compra_estado` SET `guardar`='"+guardarCompraBox.getSelectedItem().toString()+
                "',`mirar`='"+entrarboxcompra.getSelectedItem().toString()+"',`nom_usuario`='"+usuariobox.getSelectedItem().toString()+
                "' WHERE nom_usuario='"+usuariobox.getSelectedItem().toString()+"'");
     
            int a = pst.executeUpdate();
            if (a > 0) {
                JOptionPane.showMessageDialog(null, "Modificacion exitosa permisos Compra para: "+usuariobox.getSelectedItem().toString());
                //logger.info("se registra exitosamente la factura");
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
                //logger.info("hubo error al agregar la factura");
            }
        }catch(Exception e){
        }
         
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void desbloqueoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desbloqueoMouseClicked
        // TODO add your handling code here:
        
        try{
        PreparedStatement pst = cn.prepareStatement("UPDATE vendedor SET bloqueo='activo' WHERE usuario='" +usuariobox.getSelectedItem().toString() + "'");
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "El usuario "+usuariobox.getSelectedItem().toString()+" a sido desbloqueado");
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_desbloqueoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new permisos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarbtn;
    private javax.swing.JComboBox<String> categoriabox;
    private javax.swing.JButton desbloqueo;
    private javax.swing.JComboBox<String> eliminarCliBox;
    private javax.swing.JComboBox<String> eliminarProduBox;
    private javax.swing.JComboBox<String> eliminarProvBox2;
    private javax.swing.JComboBox<String> eliminarbox;
    private javax.swing.JComboBox<String> entrarbox;
    private javax.swing.JComboBox<String> entrarboxcli;
    private javax.swing.JComboBox<String> entrarboxcompra;
    private javax.swing.JComboBox<String> entrarboxprodu;
    private javax.swing.JComboBox<String> entrarboxprov;
    private javax.swing.JComboBox<String> entrarboxventa;
    private javax.swing.JComboBox<String> guardarCliBox;
    private javax.swing.JComboBox<String> guardarCompraBox;
    private javax.swing.JComboBox<String> guardarProduBox;
    private javax.swing.JComboBox<String> guardarProvBox;
    private javax.swing.JComboBox<String> guardarVentaBox;
    private javax.swing.JComboBox<String> guardarbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> modificarClibox;
    private javax.swing.JComboBox<String> modificarProdubox;
    private javax.swing.JComboBox<String> modificarProvbox;
    private javax.swing.JComboBox<String> usuariobox;
    // End of variables declaration//GEN-END:variables
}
