/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empleados;

import Clientes.RegistroClientes;
import Conexiones.ConexionSQL;
import Contacto.Contacto;
import FacturaCompra.FacturaCompra;
import Factura_Venta.Factura_Venta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menuPrincipal;

/**
 *
 * @author luisc
 */
public class RegistrarEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarEmpleados
     */
    Connection conectar = null;
    
    
    public RegistrarEmpleados() {
        initComponents();
        mostrardatos("");
        limpiar();
        bloquear();
    }
    void mostrardatos(String valor){
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Empleado");
        modelo.addColumn("Nombre Empleado");
        modelo.addColumn("Apellido Empleado");
        modelo.addColumn("Numero de Identidad Empleado");
        modelo.addColumn("Direccion Empleado");
       
        
        tablaempleados.setModel(modelo);
        String sql = "";
        if(valor.equals("")){
            sql= "SELECT * From vendedor";
        }
        else{
            sql="SELECT * FROM vendedor WHERE (vendedor_id='"+valor+"' OR nombre_empleado='"+valor+"' OR apellido_empleado='"+valor+"'OR num_identidad_empleado='"+valor+"'OR direccion='"+valor+"'OR usuario='"+"'OR pass='"+valor+"')";
            }
        String[] datos = new String[7];
        try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                
                modelo.addRow(datos);
                
            }    
        }catch(SQLException ex){
               
        }
        }
    void limpiar(){
        id_empleado.setText("");
        nom_empleado.setText("");
        apelld_empleado.setText("");
        num_id_emplea.setText("");
        dir_empleado.setText("");
        txt_usuario.setText("");
        txt_pass.setText("");
        
        
        
    }
     void desbloquear(){
        id_empleado.setEnabled(true);
        nom_empleado.setEnabled(true);
        apelld_empleado.setEnabled(true);
        num_id_emplea.setEnabled(true);
        dir_empleado.setEnabled(true);
        txt_usuario.setEnabled(true);
        txt_pass.setEnabled(true);
        save_empleado.setEnabled(true);
        nuevo.setEnabled(true);
        btn_editar.setEnabled(true);
        del_empleado.setEnabled(true);
        salir_btn.setEnabled(true);
        
    }
    void bloquear(){
        id_empleado.setEnabled(false);
        nom_empleado.setEnabled(false);
        apelld_empleado.setEnabled(false);
        num_id_emplea.setEnabled(false);
        dir_empleado.setEnabled(false);
        txt_usuario.setEnabled(false);
        txt_pass.setEnabled(false);
        
        save_empleado.setEnabled(false);
        nuevo.setEnabled(true);
        btn_editar.setEnabled(true);
        del_empleado.setEnabled(true);
        salir_btn.setEnabled(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        idEmpleado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_empleado = new javax.swing.JTextField();
        nom_empleado = new javax.swing.JTextField();
        apelld_empleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        num_id_emplea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        save_empleado = new javax.swing.JButton();
        del_empleado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaempleados = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        salir_btn = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dir_empleado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        buscar_txt = new javax.swing.JButton();
        buscar_txt_boz = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        jTextField1.setText("Registro de Empleados");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idEmpleado.setText("ID Empleado");

        jLabel2.setText("Nombre Empleado");

        jLabel3.setText("Apellido Empleado");

        id_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_empleadoActionPerformed(evt);
            }
        });
        id_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_empleadoKeyTyped(evt);
            }
        });

        nom_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_empleadoActionPerformed(evt);
            }
        });
        nom_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nom_empleadoKeyTyped(evt);
            }
        });

        apelld_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelld_empleadoActionPerformed(evt);
            }
        });
        apelld_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apelld_empleadoKeyTyped(evt);
            }
        });

        jLabel4.setText("Numero De Identidad Empleado");

        num_id_emplea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_id_empleaActionPerformed(evt);
            }
        });
        num_id_emplea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                num_id_empleaKeyTyped(evt);
            }
        });

        jLabel5.setText("Direccion del Empleado");

        save_empleado.setText("Guardar");
        save_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_empleadoActionPerformed(evt);
            }
        });

        del_empleado.setText("Eliminar");
        del_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_empleadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Registro Empleados");

        tablaempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaempleados.setComponentPopupMenu(jPopupMenu1);
        tablaempleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaempleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaempleados);

        jButton4.setText("Registrar Cliente");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Registrar Venta");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Registrar Compra");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        salir_btn.setText("Salir");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        jButton3.setText("Inicio");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        dir_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dir_empleadoKeyTyped(evt);
            }
        });

        jButton1.setText("REGISTRAR PROVEEDOR");

        jButton2.setText("Info. contacto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Usuario");

        jLabel7.setText("Contraseña");

        buscar_txt.setText("Buscar");
        buscar_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_txtActionPerformed(evt);
            }
        });

        jButton5.setText("Atras");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setText("<Anterior");

        jButton9.setText("Siguiente>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(buscar_txt_boz, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buscar_txt))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(dir_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                                    .addComponent(num_id_emplea, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_usuario)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(idEmpleado)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(apelld_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nom_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(103, 103, 103))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(save_empleado)
                                                    .addComponent(nuevo)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btn_editar)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jButton2))
                                                    .addComponent(del_empleado)
                                                    .addComponent(jButton5)
                                                    .addComponent(salir_btn))
                                                .addGap(11, 11, 11))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton9)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar_txt)
                    .addComponent(buscar_txt_boz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idEmpleado)
                            .addComponent(id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nom_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apelld_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(num_id_emplea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(dir_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(81, 81, 81)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_editar)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(del_empleado)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(salir_btn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void id_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_empleadoActionPerformed
        // TODO add your handling code here:
        id_empleado.transferFocus();
    }//GEN-LAST:event_id_empleadoActionPerformed

    private void apelld_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelld_empleadoActionPerformed
        // TODO add your handling code here:
        apelld_empleado.transferFocus();
    }//GEN-LAST:event_apelld_empleadoActionPerformed

    private void nom_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_empleadoActionPerformed
        // TODO add your handling code here:
        nom_empleado.transferFocus();
    }//GEN-LAST:event_nom_empleadoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void num_id_empleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_id_empleaActionPerformed
        // TODO add your handling code here:
        num_id_emplea.transferFocus();
        
    }//GEN-LAST:event_num_id_empleaActionPerformed

    private void save_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_empleadoActionPerformed
      
     
        ConexionSQL cc = new ConexionSQL();
        
        Connection cn = cc.getConnection();
        
    if(id_empleado.getText().equals("") || nom_empleado.getText().equals("") || apelld_empleado.getText().equals("") 
                || num_id_emplea.getText().equals("") || dir_empleado.getText().equals("") || txt_usuario.getText().equals("")
                || txt_pass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay Campos que estan vacios debe llenar todos los campos");
        
    }else{
        try {
           
            if(existeUsuario(txt_usuario.getText())==0){
              if(esUsuario(txt_usuario.getText())){
                
                
            PreparedStatement pst = cn.prepareStatement("INSERT INTO vendedor(Vendedor_id,nombre_empleado,apellido_empleado,num_identidad_empleado,direccion,usuario,pass) VALUES(?,?,?,?,?,?,?)");
            pst.setString(1, id_empleado.getText());
            pst.setString(2, nom_empleado.getText());
            pst.setString(3, apelld_empleado.getText());
            pst.setString(4, num_id_emplea.getText());
            pst.setString(5, dir_empleado.getText());
            pst.setString(6, txt_usuario.getText());
            pst.setString(7, txt_pass.getText());
            
            
            int a=pst.executeUpdate();
        if(a>0){
            JOptionPane.showMessageDialog(null,"Registro Guardado con exito");
       
            mostrardatos(""); 
        }else{
           JOptionPane.showMessageDialog(null,"Error al agregar");
        }
            }else{
                JOptionPane.showMessageDialog(null, "el usuario ya existe");
            }
            }else{
            }JOptionPane.showMessageDialog(null, "el usuario no es valido");
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_save_empleadoActionPerformed

    private int existeUsuario(String usuario) {                                              
      
        ConexionSQL cc = new ConexionSQL();
        
        Connection cn = cc.getConnection();
        
        ResultSet rs = null;
        PreparedStatement ps = null;
        
        String sql = "SELECT count(Vendedor_id) FROM vendedor WHERE usuario = ?";
    
        try {
            ps = cn.prepareStatement(sql);
            ps.setString(1, usuario);
            rs = ps.executeQuery();
            
            if(rs.next()){
                return rs.getInt(1);
            }
        } catch (Exception e) {
            return 1;
        }
        return 1;
    }
    
    
  public boolean esUsuario(String correo){
    
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.+)"+
        "[A-Za-z0-9-]+");
    
   
        Matcher matcher = pattern.matcher(correo);
        return matcher.find();
    }
    
    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        this.id_empleado.setText("");
        this.nom_empleado.setText("");
        this.apelld_empleado.setText("");
        this.num_id_emplea.setText("");
        this.dir_empleado.setText("");
        this.txt_usuario.setText("");
        this.txt_pass.setText("");
        
        this.id_empleado.grabFocus();
        
        desbloquear();
    }//GEN-LAST:event_nuevoActionPerformed

        String id = "";
    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
       desbloquear();
               
       ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        
        try{
            PreparedStatement pst = cn.prepareStatement("UPDATE vendedor SET Vendedor_id='"+id_empleado.getText()+"',nombre_empleado='"+nom_empleado.getText()+"',apellido_empleado='"+apelld_empleado.getText()+"',num_identidad_empleado='"+num_id_emplea.getText()+"',direccion='"+dir_empleado.getText()+"'WHERE Vendedor_id='"+id+"'");
            id = id_empleado.getText();
            pst.executeUpdate();
            mostrardatos("");
            JOptionPane.showMessageDialog(null,"Se a modificado con exito");
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_btn_editarActionPerformed

    private void del_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_empleadoActionPerformed
        // TODO add your handling code here:
        ConexionSQL cc = new ConexionSQL();
        Connection cn = cc.getConnection();
        int fila = tablaempleados.getSelectedRow();
        String cod = "";
        cod = tablaempleados.getValueAt(fila, 0).toString();
        try{
            PreparedStatement pst = cn.prepareStatement("DELETE * FROM vendedor where Vendedor_id='");
            id = id_empleado.getText();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        bloquear();
        limpiar();
    }//GEN-LAST:event_del_empleadoActionPerformed

    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_salir_btnActionPerformed

    private void tablaempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaempleadosMouseClicked
        // TODO add your handling code here:
        int fila_seleccionada = tablaempleados.getSelectedRow();
        id_empleado.setText(tablaempleados.getValueAt(fila_seleccionada,0).toString());
        nom_empleado.setText(tablaempleados.getValueAt(fila_seleccionada,1).toString());
        apelld_empleado.setText(tablaempleados.getValueAt(fila_seleccionada,2).toString());
        num_id_emplea.setText(tablaempleados.getValueAt(fila_seleccionada,3).toString());
        dir_empleado.setText(tablaempleados.getValueAt(fila_seleccionada,4).toString());
        txt_usuario.setText(tablaempleados.getValueAt(fila_seleccionada, 5).toString());
        txt_pass.setText(tablaempleados.getValueAt(fila_seleccionada, 6).toString());
    }//GEN-LAST:event_tablaempleadosMouseClicked

    
   
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
     menuPrincipal menu = new menuPrincipal();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      RegistroClientes registrar2 = new RegistroClientes();
 registrar2.setVisible (true);
 this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
     Factura_Venta facv = new Factura_Venta();
facv.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
    FacturaCompra facc = new FacturaCompra();
facc.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       Contacto cont = new Contacto();
       cont.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void buscar_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_txtActionPerformed
        // TODO add your handling code here:
        mostrardatos(buscar_txt_boz.getText());
    }//GEN-LAST:event_buscar_txtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        menuPrincipal menu = new menuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:\
        
        String id = "";
        int fila = tablaempleados.getSelectedRow();
        if(fila >=0){
        
        id_empleado.setText(tablaempleados.getValueAt(fila, 0).toString());
         nom_empleado.setText(tablaempleados.getValueAt(fila, 1).toString());
         apelld_empleado.setText(tablaempleados.getValueAt(fila,2).toString());
         num_id_emplea.setText(tablaempleados.getValueAt(fila, 3).toString());
         dir_empleado.setText(tablaempleados.getValueAt(fila, 4).toString());
         
         id = tablaempleados.getValueAt(fila, 0).toString();
        }else{
            JOptionPane.showMessageDialog(null, "No se encontro fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void id_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_empleadoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();
        
    }//GEN-LAST:event_id_empleadoKeyTyped

    private void nom_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_empleadoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((c<'a' || c>'z')&& (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_nom_empleadoKeyTyped

    private void apelld_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apelld_empleadoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((c<'a' || c>'z')&& (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_apelld_empleadoKeyTyped

    private void num_id_empleaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_id_empleaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_num_id_empleaKeyTyped

    private void dir_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dir_empleadoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((c<'a' || c>'z')&& (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_dir_empleadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegistrarEmpleados().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apelld_empleado;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton buscar_txt;
    private javax.swing.JTextField buscar_txt_boz;
    private javax.swing.JButton del_empleado;
    private javax.swing.JTextField dir_empleado;
    private javax.swing.JLabel idEmpleado;
    private javax.swing.JTextField id_empleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nom_empleado;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextField num_id_emplea;
    private javax.swing.JButton salir_btn;
    private javax.swing.JButton save_empleado;
    private javax.swing.JTable tablaempleados;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables


}
